"""Generate multimodal dataset — symptom text + lab report text + vitals."""
import pandas as pd, numpy as np, random, os
random.seed(42); np.random.seed(42)

DISEASES = {
    "Coronary Artery Disease":{"texts":["chest pain pressure radiating to arm jaw shortness of breath on exertion","squeezing chest discomfort triggered by activity relieved by rest sweating","angina chest tightness nausea during exercise fatigue dizziness","recurring chest pressure left arm pain cold sweats breathlessness"],"reports":["ECG: ST-segment depression T-wave inversion leads V4-V6. Echo: EF 45% wall motion abnormality. Troponin I: 0.8 ng/mL elevated. LDL: 180 mg/dL","Stress test positive. Coronary angiography: 70% stenosis LAD. Total cholesterol: 240. HDL: 38. LDL: 165 mg/dL. CK-MB elevated","2D Echo: Regional wall motion abnormality anterior wall. ECG: Q waves V1-V4. Troponin elevated. Serum creatinine: 1.2","CT coronary angiography: calcified plaques LAD and RCA. EF 50%. BNP 250 pg/mL. LDL 172 mg/dL. HbA1c 7.2%"],"age":(45,80),"fever":(36.5,37.2),"bp_s":(130,180),"bp_d":(85,110),"hr":(60,90),"gender":None},
    "Stroke":{"texts":["sudden face drooping arm weakness slurred speech severe headache vision loss","sudden numbness one side confusion difficulty speaking balance problems","sudden severe headache vision problems face arm leg weakness","sudden confusion trouble understanding speech one sided weakness coordination loss"],"reports":["CT brain: hyperdense MCA sign loss of grey-white differentiation. MRI DWI: acute infarct left MCA territory. BP: 190/110","MRI brain: acute ischemic infarct right frontal lobe. ECG: atrial fibrillation. Carotid Doppler: 80% stenosis ICA","CT head: hemorrhagic transformation right basal ganglia. INR: 3.8. Platelet: 95000. PT elevated","MRI brain DWI: restricted diffusion posterior circulation. Echo: thrombus left atrium. INR: 1.2. BP: 200/115"],"age":(50,85),"fever":(36.5,38.0),"bp_s":(150,200),"bp_d":(90,120),"hr":(60,100),"gender":None},
    "Hypertension":{"texts":["severe persistent headache dizziness blurred vision nosebleed palpitations","pounding headache at back of head shortness of breath chest pain","throbbing headache visual disturbances fatigue neck pain","frequent headaches feeling of pressure dizziness when standing"],"reports":["BP: 168/104 mmHg repeatedly. ECG: LVH. Urine microalbumin: 45 mg/g. Serum creatinine: 1.4. Fundoscopy: AV nipping","Ambulatory BP monitoring: 24h average 162/98. Echo: concentric LVH EF 60%. Renal Doppler: normal. Uric acid: 7.8","BP 175/110. Renal function: creatinine 1.3. K+: 3.2. Aldosterone:renin ratio elevated. Adrenal CT: normal","BP: 180/115. Urinalysis: protein 2+. CBC: normal. Fundoscopy: Grade III hypertensive retinopathy. HbA1c: 6.4"],"age":(35,80),"fever":(36.5,37.2),"bp_s":(140,200),"bp_d":(90,125),"hr":(70,100),"gender":None},
    "Heart Failure":{"texts":["swollen ankles feet legs shortness of breath lying flat fatigue weight gain","breathlessness at rest or activity swollen legs gasping for air at night","persistent cough wheezing swelling abdomen fatigue reduced exercise capacity","extreme fatigue swollen feet ankles difficulty breathing when lying down"],"reports":["Echo: EF 30% dilated LV severe MR. BNP: 1200 pg/mL. CXR: cardiomegaly pulmonary edema. Creatinine: 1.8","2D Echo: EF 25% global hypokinesia. NT-proBNP: 4500. CXR: bilateral pleural effusion. Na: 132 mEq/L","Cardiac MRI: EF 35% fibrosis pattern. BNP: 850. Serum albumin: 2.8. ECG: LBBB","Echo: EF 40% diastolic dysfunction grade III. BNP 620. CXR: vascular congestion. Creatinine: 2.1. K+: 5.2"],"age":(55,85),"fever":(36.5,37.5),"bp_s":(100,140),"bp_d":(60,90),"hr":(80,120),"gender":None},
    "Peripheral Artery Disease":{"texts":["leg pain cramping when walking relieved by rest cold feet poor wound healing","painful cramping thighs calves during activity numbness in legs shiny skin","leg pain at night cold pale legs slow healing sores on feet absent pulse","cramping leg pain walking stops at rest weak leg muscles hair loss on legs"],"reports":["ABI: 0.55 right leg 0.62 left. Doppler: significant stenosis SFA bilaterally. LDL: 155. HbA1c: 8.2%","CT angiography: occlusion distal SFA reconstitution at popliteal. ABI: 0.48. Wound culture: Pseudomonas","Duplex ultrasound: 70% stenosis iliac artery. ABI: 0.6. Cholesterol: 225. Triglycerides: 320","MR angiography: multisegment PAD femoropopliteal. Ankle pressure: 60 mmHg. Toe-brachial index: 0.4"],"age":(50,80),"fever":(36.5,37.2),"bp_s":(130,170),"bp_d":(80,110),"hr":(65,90),"gender":"M"},
    "COPD":{"texts":["chronic progressive shortness of breath persistent cough with mucus wheezing barrel chest","breathlessness during activities chronic productive cough chest tightness infections","worsening breathlessness frequent respiratory infections morning cough phlegm","long term cough thick phlegm increasing breathlessness difficulty breathing"],"reports":["Spirometry: FEV1/FVC 0.52 FEV1 48% predicted GOLD Stage III. CXR: hyperinflation flat diaphragm. DLCO reduced","PFT: FEV1 55% predicted irreversible obstruction. CT chest: emphysematous changes upper lobes mucus plugging","ABG: pH 7.35 PaO2 58 PaCO2 52. Spirometry: FEV1 40% predicted. Echo: pulmonary hypertension","HRCT: centrilobular emphysema bronchiectasis. FEV1 62%. SpO2 88% room air. Alpha-1 antitrypsin: normal"],"age":(45,80),"fever":(36.5,38.0),"bp_s":(120,150),"bp_d":(75,95),"hr":(75,105),"gender":"M"},
    "Asthma":{"texts":["wheezing shortness of breath chest tightness dry cough at night exercise triggered","episodic breathlessness triggered by allergens dust cold air chest tightness","frequent coughing attacks wheezing difficulty exhaling nighttime symptoms","tight chest breathless after walking coughing fits whistling sound when breathing"],"reports":["Spirometry: FEV1/FVC 0.68 18% reversibility post-bronchodilator. IgE: 480 IU/mL. Eosinophils: 8%. FeNO: 45 ppb","PFT: mild obstruction significant reversibility 22%. Skin prick test: positive HDM cat dander. IgE 320","Peak flow variability >20%. Methacholine challenge: PC20 2.4 mg/mL. CXR: hyperinflation. Eosinophils 6%","Spirometry: FEV1 72% reversible. FeNO 62 ppb. IgE 540. Sputum eosinophilia. Allergen panel: positive multiple"],"age":(5,65),"fever":(36.5,37.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(80,110),"gender":None},
    "Pneumonia":{"texts":["productive cough yellow green mucus high fever chest pain while breathing difficulty breathing","difficulty breathing rattling sounds chest fever chills sweating","sharp chest pain coughing phlegm fever fatigue loss of appetite confusion","breathing difficulty green sputum high fever rapid breathing dehydration"],"reports":["CXR: right lower lobe consolidation. WBC: 18000 neutrophilia. CRP: 145. PCT: 2.8 ng/mL. SpO2: 91%","CT chest: multilobar consolidation bilateral. Sputum culture: Streptococcus pneumoniae. WBC 22000. CRP 210","CXR: left lower lobe opacity. Blood culture: positive gram-positive cocci. WBC 16500. Na: 128. Urea: 12","HRCT: ground glass opacities bilateral. Urine antigen: positive Legionella. LDH: 380. WBC 14000"],"age":(5,85),"fever":(38.5,41.0),"bp_s":(100,135),"bp_d":(65,90),"hr":(95,125),"gender":None},
    "Tuberculosis":{"texts":["persistent cough 3 weeks coughing blood night sweats unexplained weight loss fatigue","chronic productive cough fever night sweats significant weight loss weakness","bloody sputum prolonged cough chest pain fever loss of appetite","weeks of coughing night sweats unexplained weight loss fatigue hemoptysis"],"reports":["Sputum AFB: 3+ positive. CXR: right upper lobe cavitation bilateral infiltrates. Mantoux: 22mm. GeneXpert: MTB detected RIF sensitive","HRCT: tree-in-bud pattern cavities upper lobes. Sputum culture: MTB positive. HIV: negative. LFT: mildly elevated","CXR: bilateral miliary pattern. Sputum GeneXpert: MTB+. IGRA positive. ADA elevated","CT: mediastinal lymphadenopathy calcified nodes pleural effusion. ADA: 62 U/L. Sputum ZN stain: 2+"],"age":(15,70),"fever":(37.5,39.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(80,110),"gender":None},
    "Lung Cancer":{"texts":["persistent worsening cough with blood chest pain hoarseness unexplained weight loss","new persistent cough hoarseness chest pain loss of appetite fatigue","chronic cough with blood weight loss shoulder pain bone pain headache","worsening breathlessness persistent chest pain blood in sputum weight loss"],"reports":["CT chest: 4.5cm spiculated mass RUL mediastinal LN. PET: hypermetabolic SUV 14. Biopsy: adenocarcinoma EGFR mutant","CXR: right hilar mass. CT: 3.8cm mass satellite nodules. Bronchoscopy biopsy: squamous cell carcinoma. CEA: 45","HRCT: 6cm central mass. PET-CT: M1 disease liver bone. EBUS: SCLC. LDH: 560. NSE: 88","CT: peripheral 2.8cm GGO RLL. VATS biopsy: stage IA adenocarcinoma. EGFR: exon 19 deletion. PD-L1: 60%"],"age":(45,80),"fever":(37.0,38.5),"bp_s":(110,150),"bp_d":(70,95),"hr":(75,105),"gender":"M"},
    "Diabetes Type 1":{"texts":["extreme thirst frequent urination unintentional weight loss blurred vision ketone breath","increased hunger despite eating fatigue blurred vision slow healing nausea vomiting","frequent urination extreme hunger weight loss bedwetting in children","sudden weight loss excessive thirst frequent urination nausea abdominal pain"],"reports":["FBS: 310 mg/dL. HbA1c: 11.8%. C-peptide: 0.2 ng/mL low. GAD antibody: positive. Urine ketones: 3+. pH: 7.28","Random glucose: 420 mg/dL. Ketones serum: 4.5 mmol/L. pH: 7.22 DKA. C-peptide undetectable. Anti-islet Ab positive","HbA1c: 13.2%. FBS: 380. Insulin: 2 uIU/mL low. IA-2 antibody positive. Urine protein: trace. K+: 5.8","Blood glucose: 290 mg/dL. Venous pH: 7.30. Bicarbonate: 16. Anion gap: 18. GAD65 Ab: 45 U/mL. Ketones 2+"],"age":(5,30),"fever":(36.5,37.5),"bp_s":(110,140),"bp_d":(70,90),"hr":(75,100),"gender":None},
    "Diabetes Type 2":{"texts":["frequent urination excessive thirst blurred vision fatigue weight gain tingling feet","slow healing wounds tingling feet increased hunger dry mouth frequent infections","constantly thirsty urinating a lot feeling tired numbness in feet dark patches","blurry vision frequent urination dark patches on skin fatigue weight gain"],"reports":["FBS: 178 mg/dL. PPBS: 280. HbA1c: 9.2%. Urine microalbumin: 85 mg/day. LDL: 145. Creatinine: 1.1","HbA1c: 10.4%. Fasting insulin: 28 uIU/mL high. HOMA-IR: 8.2. LFT: fatty liver. TSH: normal. BMI: 31","OGTT: 0h 126 2h 242 mg/dL. HbA1c: 8.8%. Triglycerides: 285. HDL: 32. Urine ACR: 120 mg/g","Random glucose: 320 mg/dL. HbA1c: 11%. Urine ketones: trace. LDL: 168. Creatinine: 1.3. eGFR: 62"],"age":(35,75),"fever":(36.5,37.5),"bp_s":(120,165),"bp_d":(75,105),"hr":(70,95),"gender":None},
    "Chronic Kidney Disease":{"texts":["reduced urine output swollen ankles legs fatigue nausea vomiting itching","fatigue weakness shortness of breath swelling feet ankles nausea poor appetite","persistent itching muscle cramps changes in urine output confusion decreased urine","swollen feet ankles fatigue persistent nausea poor appetite itching high BP"],"reports":["Serum creatinine: 4.8 mg/dL. eGFR: 14 mL/min Stage 5. Urine protein: 3.5 g/day. K+: 5.8. Hb: 8.2. PTH: 450","Creatinine: 3.2. BUN: 68. eGFR: 22. Urine ACR: 850 mg/g. USG: bilateral small kidneys. Anemia of CKD","Renal biopsy: focal segmental glomerulosclerosis. Creatinine: 2.8. 24h urine protein: 4.2g. BP: 168/102","Creatinine: 5.6. eGFR: 8. Phosphorus: 6.8. Ca: 7.2. PTH: 820. CXR: pulmonary edema. Dialysis initiated"],"age":(40,80),"fever":(36.5,37.8),"bp_s":(140,185),"bp_d":(85,115),"hr":(70,100),"gender":None},
    "Liver Cirrhosis":{"texts":["jaundice yellowing skin eyes swollen abdomen fatigue easy bruising spider veins","ascites swollen abdomen jaundice spider veins fatigue loss of appetite","yellowing skin eyes dark urine itching fluid in abdomen confusion muscle wasting","abdominal pain swelling jaundice confusion easy bleeding bruising weakness"],"reports":["USG: coarse liver echotexture splenomegaly ascites. Bilirubin: 4.8. ALT: 68. AST: 92. Albumin: 2.4. INR: 2.1","Liver biopsy: Metavir F4 cirrhosis. Portal hypertension on Doppler. Bilirubin: 6.2. PT: 18s. Na: 128. Plt: 82000","FibroScan: 28 kPa cirrhosis. Endoscopy: grade III varices. AFP: 12. HBsAg: positive. Child-Pugh: B","CT abdomen: nodular liver splenomegaly 18cm moderate ascites. MELD: 22. HCV RNA: 2.4M IU/mL. INR: 2.6"],"age":(40,75),"fever":(37.0,38.5),"bp_s":(100,135),"bp_d":(65,90),"hr":(75,110),"gender":"M"},
    "Obesity":{"texts":["excessive weight gain breathlessness on exertion joint pain fatigue snoring sleep apnea","difficulty physical activity excessive sweating joint pain sleep apnea back pain","back pain knee pain breathlessness on activity poor sleep obese BMI over 30","weight gain fatigue joint pain sleep apnea high BP fatty liver"],"reports":["BMI: 38.4 kg/m2. HbA1c: 6.8%. TG: 320. HDL: 28. LFT: elevated ALT/AST NAFLD. Sleep study: OSA AHI 32","BMI 42. Waist: 115cm. Lipid profile: TG 420 LDL 178. FBS: 118. HOMA-IR: 6.2. Echo: diastolic dysfunction","BMI 36. DEXA: fat mass 52%. Leptin: 48 ng/mL elevated. Thyroid: normal. Cortisol: normal. Sleep apnea confirmed","BMI 44. HbA1c: 7.2%. BP: 155/95. USG: Grade III fatty liver. TG: 380. Knee X-ray: OA changes"],"age":(20,65),"fever":(36.5,37.2),"bp_s":(130,175),"bp_d":(80,110),"hr":(75,100),"gender":None},
    "Alzheimer's Disease":{"texts":["progressive memory loss confusion disorientation difficulty daily tasks personality changes","forgetting recent events difficulty problem solving getting lost familiar places","memory problems difficulty with words repeating questions forgetting names","confusion about time place people memory decline daily function difficulty"],"reports":["MRI brain: hippocampal atrophy bilateral cortical thinning temporal lobe. PET FDG: temporoparietal hypometabolism. MMSE: 18/30","CSF: Abeta42 reduced total tau 680 phospho-tau 98 Alzheimer pattern. MRI: medial temporal atrophy. MMSE 14","Amyloid PET: diffuse amyloid deposition. Neuropsychological testing: memory 5th percentile. APOE4 genotype positive","MRI: global atrophy hippocampal volume below 10th percentile. CDR: 1.0. ADAS-cog: 28. CBC metabolic panel: normal"],"age":(65,90),"fever":(36.5,37.2),"bp_s":(120,155),"bp_d":(75,95),"hr":(65,90),"gender":"F"},
    "HIV/AIDS":{"texts":["persistent fever swollen lymph nodes fatigue recurring infections night sweats weight loss","repeated opportunistic infections night sweats unexplained weight loss chronic diarrhea","chronic diarrhea weight loss fever swollen lymph glands fatigue thrush","frequent infections sores won't heal night sweats fatigue wasting"],"reports":["HIV ELISA/Western blot: positive. CD4: 180 cells/uL. Viral load: 85000 copies/mL. PCP prophylaxis. CMV IgG+","HIV RNA: 240000. CD4: 52 AIDS. Opportunistic: PCP on BAL. CD4/CD8 ratio: 0.15. TB IGRA: positive","4th gen HIV Ag/Ab: reactive. Confirmatory: positive. CD4: 340. VL: 45000. HBsAg: negative. ART started","CD4: 28 cells/uL. VL: 1.2M. CMV retinitis on fundoscopy. Cryptococcal Ag: positive. Hb: 8.4. Plt: 78000"],"age":(18,60),"fever":(37.5,39.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(80,110),"gender":None},
    "Malaria":{"texts":["cyclic high fever chills shaking sweating headache nausea after mosquito exposure","periodic fever every 48 72 hours body ache vomiting fatigue rigors","recurrent fever chills muscle pain headache jaundice after travel","high fever with rigors sweating cycles vomiting body pain splenomegaly"],"reports":["Peripheral smear: Plasmodium vivax ring forms 2% parasitemia. RDT: positive P.vivax. WBC: 3800. Plt: 68000. Hb: 10.2","Thick smear: P.falciparum trophozoites 5% parasitemia. RDT: Pf positive. Bilirubin: 3.8. LDH: 480. Plt: 42000","PCR: P.vivax confirmed. Smear positive. LFT: AST 78 ALT 62. Plt: 55000. Hb: 9.8. Urine: haemoglobinuria","Smear: P.malariae quartan malaria. RDT positive. CBC: Hb 10.8 Plt 72000 WBC 4200. CRP: 88. Na: 132"],"age":(5,70),"fever":(38.5,41.0),"bp_s":(95,125),"bp_d":(60,85),"hr":(90,120),"gender":None},
    "Dengue Fever":{"texts":["sudden high fever severe joint muscle pain rash headache behind eyes nausea","high temperature bone breaking pain skin rash fatigue bleeding gums","fever with rash pain behind eyes nausea low platelet count vomiting","intense headache muscle pain fever bleeding gums rash petechiae"],"reports":["NS1 antigen: positive. IgM: positive. Platelet: 38000. Hematocrit: 48% rising. WBC: 2800. LFT: ALT 185","Dengue PCR: positive serotype 2. Platelet: 22000. WBC: 2400. HCT: 52%. Albumin: 2.8. USG: pleural effusion","NS1+IgM positive. Platelet: 15000 critical. Hb: 14.8. LFT elevated. Fibrinogen: 1.2. PT prolonged. BP: 90/60","Dengue IgG/IgM: positive secondary infection. Plt: 28000. NS1+. Severe dengue shock. IV fluid resuscitation"],"age":(5,70),"fever":(38.5,41.0),"bp_s":(95,125),"bp_d":(60,85),"hr":(60,90),"gender":None},
    "Hepatitis B":{"texts":["jaundice yellow skin dark urine abdominal pain fatigue nausea loss of appetite","yellowing eyes skin fatigue abdominal discomfort nausea vomiting dark urine","dark cola urine clay stools fever fatigue jaundice right abdominal pain","right upper abdominal pain nausea vomiting jaundice fatigue spider veins"],"reports":["HBsAg: positive. HBeAg: positive. HBV DNA: 2.4 million IU/mL. ALT: 380. AST: 290. Bilirubin: 5.8. INR: 1.4","HBsAg+ Anti-HBe+. HBV DNA: 8500 IU/mL. FibroScan: 12 kPa F3. AFP: 8. ALT: 85. Platelet: 142000","Acute HBV: HBsAg+ IgM anti-HBc+. HBV DNA: 1.8M. ALT 620. Bilirubin 8.2. INR: 1.8. USG: hepatomegaly","HBsAg+. Liver biopsy: Metavir A2F3. HBV DNA: 45000. ALT: 120. GGT: 88. Platelet: 105000. AFP normal"],"age":(20,65),"fever":(37.5,39.0),"bp_s":(100,130),"bp_d":(65,85),"hr":(75,100),"gender":None},
    "Hepatitis C":{"texts":["chronic fatigue jaundice nausea joint pain dark urine liver pain right side","yellowing skin eyes fatigue loss of appetite nausea vomiting dark urine","right sided abdominal pain fatigue jaundice dark urine spider veins","persistent fatigue joint pain nausea jaundice abdominal pain"],"reports":["Anti-HCV: positive. HCV RNA: 1.8M IU/mL. Genotype 1b. FibroScan: 18 kPa cirrhosis. ALT: 95. Plt: 98000","HCV RNA: 4.2M IU/mL. Genotype 3a. Liver biopsy: F3. ALT: 78. GGT: 142. Cryoglobulin: positive","Anti-HCV reactive confirmed. HCV VL: 850000. ALT: 112. Bilirubin: 2.8. INR: 1.3. USG: coarse echotexture","HCV genotype 1a. RNA: 2.1M. FibroScan 8.5 kPa F2. ALT/AST elevated. INR: 1.1. Thyroid: normal"],"age":(25,70),"fever":(37.0,38.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(70,95),"gender":None},
    "Influenza":{"texts":["sudden high fever body aches fatigue dry cough sore throat chills","fever chills headache muscle pain runny nose sneezing fatigue","high temperature joint pain loss of appetite headache nasal congestion","shivering sweating severe body ache nasal congestion started suddenly"],"reports":["Rapid influenza test: positive Influenza A. CXR: normal. WBC: 5200 lymphopenia. CRP: 42. SpO2: 97%","PCR: Influenza A H3N2 positive. WBC: 4800. CRP: 38. Procalcitonin: 0.12. LFT: normal. Oseltamivir prescribed","Influenza B rapid test positive. CXR: no consolidation. WBC: 4200. Lymphocytes: 18%. CRP: 28. PCT: 0.08","Nasal swab: Influenza A H1N1 PCR. WBC 5600. Ferritin: 145. CRP: 55. No bacterial co-infection"],"age":(5,80),"fever":(38.0,40.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(90,110),"gender":None},
    "COVID-19":{"texts":["fever dry cough loss taste smell fatigue shortness of breath chest tightness","persistent cough high fever difficulty breathing loss of smell taste","body aches fatigue headache sore throat loss of taste smell breathlessness","dry persistent cough fever chills fatigue loss of smell taste oxygen drop"],"reports":["RT-PCR: SARS-CoV-2 positive. HRCT: 45% lung involvement bilateral GGO. CRP: 185. IL-6: 88. D-dimer: 1.8","COVID Ag: positive. CT-CAD score: 18/25. SpO2: 88%. Ferritin: 1200. LDH: 480. PT: 18s. Lymphopenia","PCR positive. HRCT: peripheral consolidation crazy paving. D-dimer: 4.2. CRP: 240. IL-6: 145","COVID Ab IgG+. CT: 60% involvement. SpO2 82% room air. Ferritin: 2800. Troponin: elevated. ICU admission"],"age":(5,85),"fever":(37.5,40.0),"bp_s":(100,135),"bp_d":(65,90),"hr":(80,115),"gender":None},
    "Cholera":{"texts":["sudden profuse watery diarrhea rice water stools vomiting severe dehydration cramps","sudden massive watery diarrhea rapid dehydration muscle cramps sunken eyes","explosive painless watery diarrhea vomiting rapid dehydration thirst weakness","profuse watery stool vomiting rapid dehydration low blood pressure tachycardia"],"reports":["Stool culture: Vibrio cholerae O1 El Tor. Electrolytes: Na 128 K 2.8 Cl 88. BUN 42. Creatinine 2.8. pH 7.22","Dark field microscopy: V.cholerae motile. Stool ELISA: positive O1. Severe dehydration. Hct 58%. IV ORS","Stool PCR: V.cholerae CTX gene positive. Na: 122. K: 2.4. HCO3: 12. Urine output: oliguric. BP 80/50","Culture: V.cholerae biotype El Tor serotype Ogawa. Na 125 K 2.6 severe dehydration. Azithromycin + ORS"],"age":(5,70),"fever":(36.5,38.5),"bp_s":(80,110),"bp_d":(50,75),"hr":(100,130),"gender":None},
    "Typhoid Fever":{"texts":["sustained high fever headache abdominal pain constipation diarrhea rose spots","prolonged fever stomach pain weakness loss of appetite relative bradycardia","stepwise rising fever abdominal discomfort headache rose colored spots on chest","persistent fever abdominal pain constipation headache weakness fatigue"],"reports":["Widal: TO 1:320 TH 1:640 significant. Blood culture: Salmonella Typhi. WBC: 3800 leukopenia. CRP: 92","Blood culture: S.Typhi 2/3 bottles. Typhidot IgM: positive. WBC 3600. Plt: 92000. LFT: AST 88 ALT 72","PCR: S.Typhi positive. Widal TO 1:160. LFT elevated. Relative bradycardia. CXR: normal. Rose spots on chest","Bone marrow culture: S.Typhi gold standard. Widal TH 1:320. WBC: 3200. Na: 128. Bili: 1.8. Ciprofloxacin Rx"],"age":(5,60),"fever":(38.5,40.5),"bp_s":(100,125),"bp_d":(65,85),"hr":(70,100),"gender":None},
    "Meningitis":{"texts":["sudden severe headache stiff neck high fever sensitivity to light vomiting seizures","neck stiffness photophobia fever severe headache rash cannot touch chin to chest","intense headache fever stiff neck vomiting confusion seizures rash","sudden high fever severe headache unable to touch chin to chest vomiting"],"reports":["CSF: opening pressure 320 WBC 4200 PMN 92% protein 280 glucose 18. Gram: gram-negative diplococci","LP: turbid CSF WBC 8500 neutrophils protein 420 glucose 12. Culture: N.meningitidis. CT: cerebral edema","CSF: lymphocytes 480 protein 120 glucose 35. India ink: positive Cryptococcus. Ag titer 1:512","CSF PCR: HSV-1. WBC 220 lymphocytes. Protein 95. Glucose 42. MRI: temporal lobe signal change"],"age":(5,50),"fever":(38.5,41.0),"bp_s":(110,145),"bp_d":(70,95),"hr":(95,130),"gender":None},
    "Breast Cancer":{"texts":["lump in breast nipple discharge skin dimpling change size swollen lymph node armpit","painless breast lump nipple retraction breast skin changes axillary swelling","new breast lump inverted nipple skin thickening breast swelling pain","lump in breast irregular borders nipple discharge skin puckering armpit lump"],"reports":["Mammogram: BIRADS 5 spiculated 2.8cm mass. Core biopsy: IDC grade II ER+88% PR+72% HER2 2+ FISH neg","USG breast: hypoechoic irregular mass 3.2cm axillary LN. Biopsy: TNBC Ki67 45%. MRI: multifocal disease","Mammogram BIRADS 4c. Stereotactic biopsy: DCIS high grade. Oncotype DX: 28. ER/PR positive HER2 negative","PET-CT: FDG-avid breast mass 4.1cm 3 axillary LN. CA 15-3: 68. Biopsy: HER2+ IDC. FISH: amplified"],"age":(30,75),"fever":(36.5,37.5),"bp_s":(110,140),"bp_d":(70,90),"hr":(65,90),"gender":"F"},
    "Colorectal Cancer":{"texts":["blood in stool change bowel habits abdominal pain unexplained weight loss","rectal bleeding persistent diarrhea constipation fatigue abdominal cramps","change stool consistency blood toilet weakness unexplained weight loss fatigue","alternating constipation diarrhea rectal bleeding narrow stools fatigue"],"reports":["Colonoscopy: 4cm ulceroproliferative mass sigmoid. Biopsy: adenocarcinoma. CEA: 45. CT: liver mets Stage IV","CT colonography: 3.5cm cecal mass. Biopsy: moderately differentiated adenocarcinoma. CEA: 28. KRAS: mutant","Colonoscopy: large polyp adenocarcinoma T3N1. MSI-H. BRAF V600E mutant. CEA: 18. PET: no distant mets","MRI rectum: T3N2 rectal adenocarcinoma. CEA: 52. HER2: negative. MMR deficient. Neoadjuvant CRT planned"],"age":(45,80),"fever":(37.0,38.5),"bp_s":(110,145),"bp_d":(70,90),"hr":(70,100),"gender":None},
    "Prostate Cancer":{"texts":["difficulty urinating weak urine stream blood in urine bone pain pelvic discomfort","frequent urination at night difficulty starting blood in semen urgency incomplete emptying","weak urine flow urgency incomplete bladder emptying pelvic pain back pain","urinary problems erectile dysfunction bone pain back hips lower urinary symptoms"],"reports":["PSA: 42 ng/mL. MRI prostate: PI-RADS 5 2.2cm lesion. Biopsy: Gleason 4+5=9. Bone scan: multiple mets","PSA: 18. TRUS biopsy: 8/12 cores adenocarcinoma. Gleason 3+4=7. CT: pelvic LN positive. Stage IIIC","PSA velocity >2 ng/mL/yr. MRI: PI-RADS 4. Fusion biopsy: Gleason 3+3=6 2 cores. PSA doubling: 8 months","PSA: 85. Bone scan: diffuse skeletal mets. PET PSMA: widespread disease. Testosterone: 580 ng/dL. Started ADT"],"age":(50,85),"fever":(36.5,37.5),"bp_s":(120,155),"bp_d":(75,100),"hr":(65,90),"gender":"M"},
    "Pancreatic Cancer":{"texts":["jaundice abdominal pain radiating to back sudden weight loss new diabetes","upper abdominal pain yellow skin dark urine greasy stools weight loss","painless jaundice back pain weight loss loss of appetite fatigue","abdominal back pain jaundice nausea unexplained weight loss fatigue"],"reports":["CECT: 4.2cm hypovascular pancreatic head mass SMV involvement. CA 19-9: 4200. ERCP biopsy: adenocarcinoma","MRI: 3.8cm body mass celiac axis encasement unresectable. CA 19-9: 2800. EUS-FNA: adenocarcinoma","PET-CT: hypermetabolic pancreatic mass SUV 9.2 liver mets. CA 19-9: 8500. CEA: 28. Stage IV","MRCP: pancreatic duct dilation 2.5cm head mass. EUS biopsy: moderately differentiated adenocarcinoma. BRCA2+"],"age":(50,80),"fever":(37.0,38.5),"bp_s":(110,145),"bp_d":(70,95),"hr":(70,100),"gender":"M"},
    "Cervical Cancer":{"texts":["abnormal vaginal bleeding after intercourse between periods menopause watery discharge","unusual vaginal discharge watery bloody pelvic pain after intercourse","postcoital bleeding irregular menstrual bleeding pelvic discomfort leg swelling","vaginal bleeding after menopause pelvic pain unusual discharge leg pain"],"reports":["Pap smear: HSIL. Colposcopy biopsy: SCC stage IIB. HPV 16 positive. MRI pelvis: parametrial invasion. SCC Ag: 8.2","Cervical biopsy: adenocarcinoma. FIGO stage IB2. PET-CT: no distant mets. HPV 18. LVSI positive","LBC: ASCUS. HPV 16/18 positive. LEEP: CIN III. Cone biopsy margins: positive. SCC Ag 1.8. MRI: confined","Biopsy: SCCA. FIGO IIIB. Hydronephrosis bilateral. CA 125: 68. PET: pelvic LN positive. Chemoradiation"],"age":(25,65),"fever":(36.5,37.8),"bp_s":(105,135),"bp_d":(65,88),"hr":(68,95),"gender":"F"},
    "Migraine":{"texts":["throbbing one sided headache nausea sensitivity light sound visual aura","severe pulsating headache vomiting visual aura cannot tolerate light","intense head pain behind one eye nausea dizziness photophobia phonophobia","pounding headache flashing lights in vision vomiting neck stiffness"],"reports":["MRI brain: normal. EEG: normal. CBC: normal. TFT: normal. Migraine with aura diagnosis. Triptan prescribed","CT head: no intracranial pathology. Visual evoked potentials: abnormal. Migraine diary: 6 attacks/month","MRI/MRA: no vascular malformation. Ophthalmology: normal fields. ESR/CRP: normal. Topiramate prophylaxis","Neuropsychological: normal. MRI: small WMHC non-specific. Allodynia present. CGRP levels elevated"],"age":(15,55),"fever":(36.5,37.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(65,90),"gender":"F"},
    "Anemia":{"texts":["extreme fatigue pale skin shortness of breath on exertion dizziness brittle nails","feeling weak tired cold hands feet headache brittle nails poor concentration","lightheadedness fast heartbeat chest pain poor concentration pale conjunctiva","chronic fatigue craving ice hair loss dizziness when standing irregular heartbeat"],"reports":["CBC: Hb 6.8 g/dL MCV 62 microcytic MCH 18 RDW 18%. Serum ferritin: 4 ng/mL. TIBC: 480. Iron: 28","Hb: 8.2. Peripheral smear: hypochromic microcytic. Reticulocyte: 0.8%. B12: 145 pg/mL low. Folate: 2.1","Hb: 7.6. MCV 108 macrocytic. B12: 88 pg/mL very low. Anti-intrinsic factor Ab: positive pernicious anemia","Hb: 9.4. Reticulocyte: 8.2% hemolysis. LDH: 680. Bili indirect: 3.2. Coombs: positive AIHA. Haptoglobin low"],"age":(15,70),"fever":(36.0,37.5),"bp_s":(95,120),"bp_d":(60,80),"hr":(85,115),"gender":"F"},
    "Gastroenteritis":{"texts":["nausea vomiting diarrhea stomach cramps low grade fever dehydration","watery diarrhea abdominal pain vomiting dehydration symptoms","sudden stomach pain loose stools feeling nauseous mild fever","cramping abdominal pain vomiting diarrhea multiple episodes"],"reports":["Stool culture: Salmonella enteritidis. WBC: 12000. CRP: 45. Electrolytes: Na 133 K 3.0. Stool: WBC 3+","Stool PCR: norovirus positive. Rotavirus Ag: negative. CBC: mild leukocytosis. Creatinine: 1.2 dehydration","Stool: Campylobacter jejuni. WBC 15000. CRP 85. Stool mucus and blood. IV fluids. Azithromycin Rx","C.difficile toxin: positive post-antibiotic. WBC 22000. CT: colonic wall thickening. Vancomycin oral"],"age":(5,75),"fever":(37.5,39.5),"bp_s":(100,125),"bp_d":(65,85),"hr":(85,110),"gender":None},
    "UTI":{"texts":["burning sensation during urination frequent urge to urinate cloudy urine pelvic pain","painful urination lower abdominal pain strong smelling urine fever","urgency to urinate blood in urine pelvic pain burning while peeing","frequent urination little output lower back pain mild fever dark urine"],"reports":["Urine culture: E.coli 100000 CFU/mL. Urine R/M: WBC 80 RBC 20 protein 1+. US: no upper tract involvement","Urine MC&S: Klebsiella pneumoniae ESBL producer. WBC 25 nitrite positive. Urine PCR: positive. Meropenem","Dipstick: leucocytes 3+ nitrites positive blood 2+. Culture: Enterococcus faecalis. CRP: 48. Urine pH: 8","Urine: Proteus mirabilis 50000 CFU. Struvite stones on USG. WBC casts: pyelonephritis. Creatinine: 1.1"],"age":(18,70),"fever":(37.5,39.5),"bp_s":(100,130),"bp_d":(65,85),"hr":(75,100),"gender":"F"},
    "Depression":{"texts":["persistent sadness loss of interest fatigue sleep problems hopelessness worthless","feeling empty crying without reason difficulty concentrating social withdrawal","low mood every day no enjoyment activities changes appetite insomnia","constant sadness insomnia low energy worthless negative thoughts withdrawal"],"reports":["PHQ-9: 22 severe. Hamilton: 28. Beck: 32. TSH: normal. CBC: normal. Cortisol morning: 28 elevated. MRI: normal","PHQ-9: 18 moderately severe. TFT: T3 low hypothyroid. B12: 185. Folate: 4.2. Sleep study: insomnia","HAMD-17: 24. Dexamethasone suppression test: non-suppressor. EEG: normal. Brain MRI: small frontal WMC","MADRS: 32 severe. 5-HIAA in urine: reduced. BDNF serum: low. ECG: normal before antidepressant. PHQ9: 20"],"age":(15,65),"fever":(36.5,37.2),"bp_s":(100,125),"bp_d":(65,82),"hr":(60,85),"gender":"F"},
    "Appendicitis":{"texts":["severe pain starting navel moving lower right abdomen fever nausea vomiting","sharp lower right abdominal pain loss of appetite vomiting fever rigidity","sudden pain right side stomach rigid abdomen cannot walk straight rebound tenderness","worsening abdominal pain nausea fever rebound tenderness right lower quadrant"],"reports":["USG: non-compressible appendix 9mm periappendiceal fat stranding. WBC: 18500 neutrophilia. CRP: 142","CT abdomen: distended appendix 11mm appendicolith periappendiceal phlegmon. WBC 22000. CRP 185. Perforation risk high","Alvarado score: 9. USG: positive appendicitis. WBC 16800. CRP 98. Laparoscopic appendicectomy done","CT: perforated appendicitis pelvic abscess 4cm. WBC 24000. CRP 320. IV antibiotics interval appendicectomy"],"age":(10,50),"fever":(38.0,40.0),"bp_s":(100,130),"bp_d":(65,85),"hr":(90,120),"gender":None},
}

records = []
for disease, cfg in DISEASES.items():
    for _ in range(120):
        g = cfg.get("gender")
        weights = [0.7,0.3] if g=="F" else [0.3,0.7] if g=="M" else [0.5,0.5]
        gender = random.choices(["Female","Male"], weights=weights)[0]
        sym  = random.choice(cfg["texts"])
        rep  = random.choice(cfg["reports"])
        extra = random.choice(["", " symptoms worsening", " started 3 days ago", " feeling unwell"])
        records.append({
            "symptom_text":  sym + extra,
            "report_text":   rep,
            "combined_text": sym + " " + rep + extra,
            "age":           random.randint(*cfg["age"]),
            "gender":        gender,
            "fever_celsius": round(random.uniform(*cfg["fever"]), 1),
            "systolic_bp":   random.randint(*cfg["bp_s"]),
            "diastolic_bp":  random.randint(*cfg["bp_d"]),
            "heart_rate_bpm":random.randint(*cfg["hr"]),
            "duration_days": random.randint(1, 21),
            "disease":       disease,
        })

random.shuffle(records)
df = pd.DataFrame(records)
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "disease_dataset.csv")
df.to_csv(out, index=False)
print(f"✅ Dataset: {len(df)} rows | {df['disease'].nunique()} diseases | columns: {list(df.columns)}")
