"""doctors_db.py — 100+ doctors, every major disease covered, real Indian doctor names"""

def _c(texts):
    return [{"user":t[0],"text":t[1],"rating":t[2],"date":t[3]} for t in texts]

DOCTORS_DB = []

# ── CARDIOLOGISTS ─────────────────────────────────────────────────────────────
_cardio_tags = ["coronary artery disease","heart failure","stroke","hypertension","peripheral artery disease"]
DOCTORS_DB += [
 {"id":101,"name":"Dr. Devi Prasad Shetty","specialty":"Cardiothoracic Surgeon","hospital":"Narayana Health, Bengaluru","city":"Bengaluru","experience":35,"degree":"MBBS, MS, MCh (Cardiac Surgery), FRCS (UK)","rating":4.9,"fee":1500,"slots":["09:00 AM","11:00 AM","03:00 PM"],"tags":_cardio_tags,"avatar":"DS","color":"#EF4444","comments":_c([("Ramesh K.","Bypass surgery was flawless. Exceptional surgeon.",5,"Mar 2025"),("Sunita M.","Explained every step before surgery. Very calm.",5,"Feb 2025"),("Arun T.","Best cardiologist in Bengaluru. Worth every minute.",4,"Jan 2025")])},
 {"id":102,"name":"Dr. Naresh Trehan","specialty":"Cardiothoracic Surgeon","hospital":"Medanta, Gurugram","city":"Gurugram","experience":40,"degree":"MBBS, MS, MCh (Cardiothoracic), FACS","rating":4.9,"fee":2000,"slots":["10:00 AM","02:00 PM","04:00 PM"],"tags":_cardio_tags,"avatar":"NT","color":"#EF4444","comments":_c([("Vikram S.","Saved my father's life. No words can describe.",5,"Mar 2025"),("Priya L.","Professional. Medanta team is outstanding.",5,"Feb 2025"),("Mohan R.","Very thorough. Clear treatment plan.",4,"Jan 2025")])},
 {"id":103,"name":"Dr. Ashok Seth","specialty":"Interventional Cardiologist","hospital":"Fortis Escorts Heart Institute, Delhi","city":"Delhi","experience":38,"degree":"MBBS, MD, DM (Cardiology), FESC, FACC","rating":4.9,"fee":1800,"slots":["09:30 AM","01:00 PM","04:30 PM"],"tags":_cardio_tags,"avatar":"AS","color":"#EF4444","comments":_c([("Rajesh B.","Pioneered cardiac procedures in India. Remarkable.",5,"Mar 2025"),("Meena C.","Stenting done. Zero complications.",5,"Feb 2025"),("Arjun D.","Clear treatment plan. Excellent follow-up.",4,"Jan 2025")])},
 {"id":104,"name":"Dr. P. K. Deb","specialty":"Cardiologist","hospital":"Apollo Hospitals, Chennai","city":"Chennai","experience":28,"degree":"MBBS, MD, DM (Cardiology), FACC","rating":4.8,"fee":1200,"slots":["08:30 AM","12:00 PM","03:30 PM"],"tags":_cardio_tags,"avatar":"PD","color":"#EF4444","comments":_c([("Kavitha N.","Diagnosed when three doctors missed it.",5,"Mar 2025"),("Suresh P.","Great with elderly patients.",5,"Feb 2025"),("Deepa V.","Excellent but long wait.",4,"Jan 2025")])},
 {"id":105,"name":"Dr. K. M. Cherian","specialty":"Cardiothoracic Surgeon","hospital":"Frontier Lifeline Hospital, Chennai","city":"Chennai","experience":45,"degree":"MBBS, MS, MCh (CTVS), FRCS, FACS","rating":4.9,"fee":2500,"slots":["10:30 AM","02:30 PM"],"tags":_cardio_tags,"avatar":"KC","color":"#EF4444","comments":_c([("Thomas J.","16,000+ open-heart surgeries. Legendary doctor.",5,"Mar 2025"),("Anita S.","Husband's valve replacement was perfect.",5,"Jan 2025"),("George M.","World-class skills and facility.",5,"Dec 2024")])},
 {"id":106,"name":"Dr. Santanu Gupta","specialty":"Cardiologist","hospital":"AMRI Hospitals, Kolkata","city":"Kolkata","experience":22,"degree":"MBBS, MD, DM (Cardiology)","rating":4.7,"fee":900,"slots":["09:00 AM","11:30 AM","04:00 PM"],"tags":_cardio_tags,"avatar":"SG","color":"#EF4444","comments":_c([("Bidhan R.","Very thorough hypertension management.",5,"Mar 2025"),("Sumita D.","Affordable yet excellent quality of care.",4,"Feb 2025"),("Pradip M.","Available on weekends. Very convenient.",4,"Jan 2025")])},
 {"id":107,"name":"Dr. Viveka Kumar","specialty":"Cardiologist","hospital":"Max Super Speciality Hospital, Delhi","city":"Delhi","experience":25,"degree":"MBBS, MD, DM (Cardiology), PhD","rating":4.8,"fee":1400,"slots":["08:00 AM","12:30 PM","03:00 PM"],"tags":_cardio_tags,"avatar":"VK","color":"#EF4444","comments":_c([("Neha A.","Father's angioplasty done with great precision.",5,"Mar 2025"),("Rohit S.","Caught blockage three doctors missed.",5,"Feb 2025"),("Pooja T.","Good. Slightly rushed but very competent.",4,"Jan 2025")])},
 {"id":108,"name":"Dr. S. Ramakrishnan","specialty":"Cardiologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":30,"degree":"MBBS, MD, DM (Cardiology), DNB","rating":4.9,"fee":500,"slots":["09:00 AM","11:00 AM","02:00 PM"],"tags":_cardio_tags,"avatar":"SR","color":"#EF4444","comments":_c([("Lalit K.","Government hospital but world-class doctor.",5,"Mar 2025"),("Savita R.","Hard to get appointment but worth the wait.",5,"Feb 2025"),("Dilip V.","AIIMS has best cardiac care in India.",5,"Jan 2025")])},
 {"id":109,"name":"Dr. Upendra Kaul","specialty":"Interventional Cardiologist","hospital":"Batra Hospital, Delhi","city":"Delhi","experience":36,"degree":"MBBS, MD, DM (Cardiology), FSCAI, FACC","rating":4.8,"fee":1600,"slots":["10:00 AM","01:30 PM","04:00 PM"],"tags":_cardio_tags,"avatar":"UK","color":"#EF4444","comments":_c([("Suresh N.","Pioneer of interventional cardiology in India.",5,"Mar 2025"),("Kavita B.","Stent procedure flawless. Recovery in two weeks.",5,"Feb 2025"),("Rajan M.","Very experienced. Straightforward about options.",4,"Jan 2025")])},
 {"id":110,"name":"Dr. Praveen Chandra","specialty":"Interventional Cardiologist","hospital":"Medanta, Gurugram","city":"Gurugram","experience":27,"degree":"MBBS, MD, DM (Cardiology), FACC, FSCAI","rating":4.9,"fee":1600,"slots":["08:00 AM","11:00 AM","03:00 PM"],"tags":_cardio_tags,"avatar":"PC","color":"#EF4444","comments":_c([("Sudhir K.","World-class angioplasty. Done perfectly.",5,"Mar 2025"),("Asha T.","Very clear about risks before procedure.",5,"Feb 2025"),("Harish B.","Excellent technical skill. No complications.",5,"Jan 2025")])},
 {"id":111,"name":"Dr. Anil Bhan","specialty":"Cardiothoracic Surgeon","hospital":"Indraprastha Apollo, Delhi","city":"Delhi","experience":30,"degree":"MBBS, MS, MCh (CTVS), FIACS","rating":4.8,"fee":2000,"slots":["11:00 AM","02:00 PM"],"tags":_cardio_tags,"avatar":"AB","color":"#EF4444","comments":_c([("Deepak K.","Double valve replacement was perfect.",5,"Mar 2025"),("Sunita R.","Very reassuring before surgery.",5,"Jan 2025"),("Mohit S.","Zero complications in complex surgery.",5,"Dec 2024")])},
 {"id":112,"name":"Dr. O. P. Yadava","specialty":"Cardiothoracic Surgeon","hospital":"National Heart Institute, Delhi","city":"Delhi","experience":33,"degree":"MBBS, MS, MCh (CTVS), PhD, FAMS","rating":4.8,"fee":1700,"slots":["10:30 AM","02:30 PM"],"tags":_cardio_tags,"avatar":"OY","color":"#EF4444","comments":_c([("Sanjay V.","Finest cardiac surgeons in Asia. Remarkable.",5,"Mar 2025"),("Meera B.","CABG surgery flawless. Full recovery.",5,"Feb 2025"),("Ashok G.","Great patient communication alongside great skill.",4,"Jan 2025")])},
 {"id":113,"name":"Dr. Y. K. Misra","specialty":"Cardiologist","hospital":"Pushpawati Singhania Hospital, Delhi","city":"Delhi","experience":32,"degree":"MBBS, MD, DM (Cardiology), FAMS","rating":4.7,"fee":1100,"slots":["09:30 AM","12:30 PM","04:30 PM"],"tags":_cardio_tags,"avatar":"YM","color":"#EF4444","comments":_c([("Anil P.","Very experienced. Excellent bedside manner.",5,"Mar 2025"),("Geeta S.","Good diagnosis. Clear medication instructions.",4,"Feb 2025"),("Ramesh D.","Treated my heart failure well. Very caring.",4,"Jan 2025")])},
 {"id":114,"name":"Dr. Ranjit Nair","specialty":"Cardiologist","hospital":"Amrita Hospital, Kochi","city":"Kochi","experience":20,"degree":"MBBS, MD, DM (Cardiology), DNB, MRCP","rating":4.8,"fee":1000,"slots":["08:30 AM","11:30 AM","03:30 PM"],"tags":_cardio_tags,"avatar":"RN","color":"#EF4444","comments":_c([("Babu K.","Best cardiac care in Kerala. Dr. Nair is exceptional.",5,"Mar 2025"),("Leela V.","Mother's hypertension fully controlled.",5,"Feb 2025"),("Krishnan P.","Very updated with latest cardiology research.",4,"Jan 2025")])},
 {"id":115,"name":"Dr. J. P. S. Sawhney","specialty":"Cardiologist","hospital":"Sir Ganga Ram Hospital, Delhi","city":"Delhi","experience":28,"degree":"MBBS, MD, DM (Cardiology), FSCAI","rating":4.7,"fee":1300,"slots":["09:00 AM","12:30 PM","03:30 PM"],"tags":_cardio_tags,"avatar":"JS","color":"#EF4444","comments":_c([("Prem K.","Excellent. Very systematic approach.",5,"Mar 2025"),("Kamla D.","Father's CAD managed well. No more angina.",5,"Feb 2025"),("Bharat S.","Good consultation. Clear prescription.",4,"Jan 2025")])},
 {"id":116,"name":"Dr. Sudhir Mehta","specialty":"Cardiologist","hospital":"Nanavati Max Hospital, Mumbai","city":"Mumbai","experience":26,"degree":"MBBS, MD, DM (Cardiology), FESC","rating":4.7,"fee":1250,"slots":["10:00 AM","01:30 PM","04:30 PM"],"tags":_cardio_tags,"avatar":"SM","color":"#EF4444","comments":_c([("Dinesh P.","Explained my BP medications clearly.",5,"Mar 2025"),("Rekha N.","Good follow-up. Always available for queries.",4,"Feb 2025"),("Nikhil T.","Found silent blockage early. Life saver.",5,"Jan 2025")])},
 {"id":117,"name":"Dr. Rakesh Yadav","specialty":"Cardiologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":22,"degree":"MBBS, MD, DM (Cardiology), DNB","rating":4.8,"fee":500,"slots":["09:30 AM","11:30 AM","02:30 PM"],"tags":_cardio_tags,"avatar":"RY","color":"#EF4444","comments":_c([("Vinay S.","AIIMS quality same as top private hospital.",5,"Mar 2025"),("Sheela R.","Very humble and knowledgeable.",5,"Feb 2025"),("Manoj K.","Long queue but Dr. Yadav is worth it.",4,"Jan 2025")])},
 {"id":118,"name":"Dr. Nithya Ramamurthy","specialty":"Cardiologist","hospital":"Kauvery Hospital, Chennai","city":"Chennai","experience":16,"degree":"MBBS, MD, DM (Cardiology), DNB","rating":4.7,"fee":900,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_cardio_tags,"avatar":"NR","color":"#EF4444","comments":_c([("Arumugam S.","Very skilled and compassionate female cardiologist.",5,"Mar 2025"),("Hema V.","Best explanation of BP medications I have received.",5,"Feb 2025"),("Ganesan K.","Good. Modern approach to heart care.",4,"Jan 2025")])},
 {"id":119,"name":"Dr. Alok Kumar Singh","specialty":"Cardiologist","hospital":"Medica Superspecialty Hospital, Kolkata","city":"Kolkata","experience":18,"degree":"MBBS, MD, DM (Cardiology)","rating":4.6,"fee":850,"slots":["09:00 AM","01:00 PM","05:00 PM"],"tags":_cardio_tags,"avatar":"AK","color":"#EF4444","comments":_c([("Tanmoy B.","Young and very updated. Uses latest protocols.",5,"Mar 2025"),("Dipali S.","Good consultation. Thorough examination.",4,"Feb 2025"),("Pritam M.","Affordable and excellent quality care.",4,"Jan 2025")])},
 {"id":120,"name":"Dr. Rajeev Rathi","specialty":"Cardiologist","hospital":"GKNM Hospital, Coimbatore","city":"Coimbatore","experience":24,"degree":"MBBS, MD, DM (Cardiology), DNB, FNAMS","rating":4.7,"fee":750,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_cardio_tags,"avatar":"RR","color":"#EF4444","comments":_c([("Murugan S.","Best cardiologist in Coimbatore. Very accessible.",5,"Mar 2025"),("Prema K.","Good treatment for mother's heart failure.",4,"Feb 2025"),("Vijay N.","Clear explanation of my condition.",4,"Jan 2025")])},
]

# ── PULMONOLOGISTS ────────────────────────────────────────────────────────────
_pulm_tags = ["copd","asthma","tuberculosis","pneumonia","lung cancer","covid-19"]
DOCTORS_DB += [
 {"id":201,"name":"Dr. Surya Kant","specialty":"Pulmonologist","hospital":"KGMU, Lucknow","city":"Lucknow","experience":28,"degree":"MBBS, MD (Pulmonary Medicine), DTCD, FCCP","rating":4.8,"fee":800,"slots":["09:00 AM","12:00 PM","03:30 PM"],"tags":_pulm_tags,"avatar":"SK","color":"#8B5CF6","comments":_c([("Ramesh G.","Best pulmonologist in Lucknow. COPD treated effectively.",5,"Mar 2025"),("Sunita K.","Expert in TB. Cleared all my misconceptions.",5,"Feb 2025"),("Anil P.","Very thorough follow-up after pneumonia.",4,"Jan 2025")])},
 {"id":202,"name":"Dr. D. Behera","specialty":"Pulmonologist","hospital":"PGIMER, Chandigarh","city":"Chandigarh","experience":35,"degree":"MBBS, MD, PhD (Pulmonary Medicine), FRCP","rating":4.9,"fee":600,"slots":["08:30 AM","11:30 AM","02:30 PM"],"tags":_pulm_tags,"avatar":"DB","color":"#8B5CF6","comments":_c([("Harpreet S.","Top authority on lung cancer in India.",5,"Mar 2025"),("Gurpreet K.","Diagnosed my TB after months of uncertainty.",5,"Feb 2025"),("Manjeet R.","Outstanding expertise. Best for complex lung cases.",5,"Jan 2025")])},
 {"id":203,"name":"Dr. Randeep Guleria","specialty":"Pulmonologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":30,"degree":"MBBS, MD, DM (Pulmonary Medicine), FAMS, FRCP","rating":4.9,"fee":500,"slots":["09:00 AM","11:00 AM","02:00 PM"],"tags":_pulm_tags,"avatar":"RG","color":"#8B5CF6","comments":_c([("Amit K.","Former AIIMS Director. Managed COVID at national level.",5,"Mar 2025"),("Priya S.","Severe COVID complications managed flawlessly.",5,"Feb 2025"),("Ravi T.","Very calm and reassuring in critical situations.",5,"Jan 2025")])},
 {"id":204,"name":"Dr. Agam Vora","specialty":"Pulmonologist","hospital":"P. D. Hinduja Hospital, Mumbai","city":"Mumbai","experience":20,"degree":"MBBS, MD (Chest & TB), FCCP, FAPSR","rating":4.7,"fee":1200,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_pulm_tags,"avatar":"AV","color":"#8B5CF6","comments":_c([("Farhan M.","Asthma under control for first time in years.",5,"Mar 2025"),("Rekha N.","Very patient. Quality time with each patient.",5,"Feb 2025"),("Santosh D.","Good diagnosis and treatment plan for COPD.",4,"Jan 2025")])},
 {"id":205,"name":"Dr. Aloke Gopal Ghoshal","specialty":"Pulmonologist","hospital":"NAABI, Kolkata","city":"Kolkata","experience":26,"degree":"MBBS, MD (Pulmonary Medicine), FCCP, FNCCP","rating":4.8,"fee":900,"slots":["09:30 AM","12:30 PM","04:00 PM"],"tags":_pulm_tags,"avatar":"AG","color":"#8B5CF6","comments":_c([("Tapas B.","Best asthma specialist. Life-changing treatment.",5,"Mar 2025"),("Mitali S.","Understood my allergy triggers completely.",5,"Feb 2025"),("Debashis M.","Very updated with latest protocols.",4,"Jan 2025")])},
 {"id":206,"name":"Dr. S. N. Gaur","specialty":"Pulmonologist","hospital":"Vallabhbhai Patel Chest Institute, Delhi","city":"Delhi","experience":34,"degree":"MBBS, MD (Chest & TB), PhD, FCCP, FNCCP, FAMS","rating":4.8,"fee":700,"slots":["09:30 AM","12:00 PM","03:00 PM"],"tags":_pulm_tags,"avatar":"SG","color":"#8B5CF6","comments":_c([("Bharat R.","Leading pulmonologist in India. Excellent for asthma research.",5,"Mar 2025"),("Anita S.","Very systematic COPD diagnosis and treatment.",5,"Feb 2025"),("Rakesh V.","Excellent institution for chest diseases.",4,"Jan 2025")])},
 {"id":207,"name":"Dr. Prashant Chhajed","specialty":"Pulmonologist","hospital":"Lung Care Clinic, Mumbai","city":"Mumbai","experience":22,"degree":"MBBS, MD, DNB (Respiratory Medicine), FCCP, EDIC","rating":4.8,"fee":1100,"slots":["10:30 AM","02:00 PM","05:00 PM"],"tags":_pulm_tags,"avatar":"PC","color":"#8B5CF6","comments":_c([("Vinod R.","Excellent bronchoscopy. Lung cancer diagnosed early.",5,"Mar 2025"),("Asha M.","COPD management improved quality of life significantly.",5,"Feb 2025"),("Deepak T.","Very updated with latest pulmonology guidelines.",4,"Jan 2025")])},
 {"id":208,"name":"Dr. Rajesh N. Solanki","specialty":"Pulmonologist","hospital":"Zydus Hospital, Ahmedabad","city":"Ahmedabad","experience":18,"degree":"MBBS, MD (Respiratory Medicine), DTCD","rating":4.6,"fee":700,"slots":["09:00 AM","01:30 PM","05:00 PM"],"tags":_pulm_tags,"avatar":"RS","color":"#8B5CF6","comments":_c([("Dhruv P.","Excellent for child's severe asthma. Very gentle.",5,"Mar 2025"),("Hetal S.","Good treatment plan. Very accessible.",4,"Feb 2025"),("Nilesh K.","Knowledgeable. Waiting time could improve.",4,"Jan 2025")])},
 {"id":209,"name":"Dr. Parvaiz A. Koul","specialty":"Pulmonologist","hospital":"SKIMS, Srinagar","city":"Srinagar","experience":26,"degree":"MBBS, MD, DM (Pulmonary Medicine), FCCP, FRCP","rating":4.8,"fee":600,"slots":["09:00 AM","11:30 AM","03:00 PM"],"tags":_pulm_tags,"avatar":"PK","color":"#8B5CF6","comments":_c([("Farooq A.","Best pulmonologist in J&K. TB treated with great care.",5,"Mar 2025"),("Rukhsana B.","Very dedicated. Excellent COPD follow-up.",5,"Feb 2025"),("Bilal M.","Outstanding expertise in lung diseases.",4,"Jan 2025")])},
 {"id":210,"name":"Dr. Ravindra Mehta","specialty":"Pulmonologist & Critical Care","hospital":"Apollo BGS Hospitals, Mysuru","city":"Mysuru","experience":19,"degree":"MBBS, MD, DNB (Respiratory Medicine), FCCP, EDIC","rating":4.7,"fee":900,"slots":["09:30 AM","01:30 PM","04:30 PM"],"tags":_pulm_tags,"avatar":"RM","color":"#8B5CF6","comments":_c([("Shyam R.","Saved my life during severe pneumonia. Brilliant ICU management.",5,"Mar 2025"),("Kavitha N.","Asthma perfectly managed.",5,"Feb 2025"),("Suresh B.","Clear explanation of my COPD stages.",4,"Jan 2025")])},
]

# ── ENDOCRINOLOGISTS ─────────────────────────────────────────────────────────
_endo_tags = ["diabetes type 1","diabetes type 2","obesity","chronic kidney disease","alzheimer's disease"]
DOCTORS_DB += [
 {"id":301,"name":"Dr. V. Mohan","specialty":"Diabetologist","hospital":"Dr. Mohan's Diabetes Centre, Chennai","city":"Chennai","experience":38,"degree":"MBBS, MD, PhD, DSc, FRCP, FNASc, FNAMS","rating":4.9,"fee":1000,"slots":["09:00 AM","11:00 AM","03:00 PM"],"tags":_endo_tags,"avatar":"VM","color":"#06B6D4","comments":_c([("Anand S.","World-renowned expert. HbA1c now perfect.",5,"Mar 2025"),("Meena R.","Very scientific approach to diabetes.",5,"Feb 2025"),("Karthik L.","Diet plan completely transformed my health.",5,"Jan 2025")])},
 {"id":302,"name":"Dr. Ambrish Mithal","specialty":"Endocrinologist","hospital":"Max Healthcare, Delhi","city":"Delhi","experience":35,"degree":"MBBS, MD, DM (Endocrinology), FRCP","rating":4.9,"fee":1500,"slots":["10:00 AM","02:00 PM","04:30 PM"],"tags":_endo_tags,"avatar":"AM","color":"#06B6D4","comments":_c([("Suresh M.","Sorted complex diabetes and thyroid issues together.",5,"Mar 2025"),("Parveen K.","Complete lifestyle overhaul plan. Very thorough.",5,"Feb 2025"),("Rita B.","Expensive but worth every rupee.",4,"Jan 2025")])},
 {"id":303,"name":"Dr. Shashank Joshi","specialty":"Endocrinologist","hospital":"Lilavati Hospital, Mumbai","city":"Mumbai","experience":22,"degree":"MBBS, MD, DM (Endocrinology), FACE","rating":4.8,"fee":1200,"slots":["09:30 AM","01:00 PM","05:00 PM"],"tags":_endo_tags,"avatar":"SJ","color":"#06B6D4","comments":_c([("Dinesh N.","Lost 12 kg following his plan. Life-changing.",5,"Mar 2025"),("Lalita P.","Explains in simple language. Very approachable.",5,"Feb 2025"),("Manoj T.","Good. Updated with latest insulin therapies.",4,"Jan 2025")])},
 {"id":304,"name":"Dr. Sanjay Kalra","specialty":"Endocrinologist","hospital":"Bharti Hospital, Karnal","city":"Karnal","experience":24,"degree":"MBBS, MD, DM (Endocrinology)","rating":4.8,"fee":800,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_endo_tags,"avatar":"SK","color":"#06B6D4","comments":_c([("Gurinder S.","Most knowledgeable diabetes doctor. Publishes extensively.",5,"Mar 2025"),("Harleen K.","Spent 45 minutes explaining my condition.",5,"Feb 2025"),("Balveer R.","Excellent. Very logical treatment approach.",4,"Jan 2025")])},
 {"id":305,"name":"Dr. C. S. Yajnik","specialty":"Endocrinologist","hospital":"KEM Hospital, Pune","city":"Pune","experience":40,"degree":"MBBS, MD, DM (Endocrinology), FRCP, FNASc","rating":4.9,"fee":900,"slots":["10:00 AM","01:00 PM"],"tags":_endo_tags,"avatar":"CY","color":"#06B6D4","comments":_c([("Suhas B.","World famous for diabetes and nutrition research.",5,"Mar 2025"),("Sunanda P.","Research on fetal origins of diabetes is groundbreaking.",5,"Feb 2025"),("Rahul N.","Long waiting list but completely worth it.",4,"Jan 2025")])},
 {"id":306,"name":"Dr. A. K. Das","specialty":"Diabetologist","hospital":"Pondicherry Institute of Medical Sciences","city":"Puducherry","experience":32,"degree":"MBBS, MD, FICP, FRCP, FACE","rating":4.8,"fee":700,"slots":["09:00 AM","11:30 AM","03:30 PM"],"tags":_endo_tags,"avatar":"AD","color":"#06B6D4","comments":_c([("Murugan R.","Best diabetes doctor in South India.",5,"Mar 2025"),("Geetha S.","Type 1 diabetes management improved tremendously.",5,"Feb 2025"),("Velu K.","Good consultation. Clear dietary guidelines.",4,"Jan 2025")])},
 {"id":307,"name":"Dr. Nihal Thomas","specialty":"Endocrinologist","hospital":"Christian Medical College, Vellore","city":"Vellore","experience":28,"degree":"MBBS, MD, DM (Endocrinology), PhD, FRCP","rating":4.9,"fee":750,"slots":["09:30 AM","12:30 PM","03:00 PM"],"tags":_endo_tags,"avatar":"NT","color":"#06B6D4","comments":_c([("Abraham J.","CMC Vellore is world-class. Dr. Thomas exceptional.",5,"Mar 2025"),("Mary K.","Type 1 diabetes managed brilliantly.",5,"Feb 2025"),("Samuel P.","Excellent. Very thorough blood work review.",5,"Jan 2025")])},
 {"id":308,"name":"Dr. Altamash Shaikh","specialty":"Endocrinologist","hospital":"Masina Hospital, Mumbai","city":"Mumbai","experience":17,"degree":"MBBS, MD, DNB (Endocrinology)","rating":4.7,"fee":1000,"slots":["10:00 AM","02:00 PM","05:00 PM"],"tags":_endo_tags,"avatar":"AS","color":"#06B6D4","comments":_c([("Iqbal M.","Young and very knowledgeable. Uses latest diabetes tech.",5,"Mar 2025"),("Fatima S.","CGM sensor usage explained perfectly.",5,"Feb 2025"),("Zuber K.","Good consultation. Very patient with questions.",4,"Jan 2025")])},
 {"id":309,"name":"Dr. Rakesh Sahay","specialty":"Endocrinologist","hospital":"Osmania Medical College, Hyderabad","city":"Hyderabad","experience":26,"degree":"MBBS, MD, DM (Endocrinology), FICP","rating":4.7,"fee":650,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_endo_tags,"avatar":"RS","color":"#06B6D4","comments":_c([("Suresh R.","Thyroid and diabetes managed together well.",5,"Mar 2025"),("Padma V.","Excellent Type 2 management explanation.",4,"Feb 2025"),("Rao K.","Affordable for quality of care given.",4,"Jan 2025")])},
 {"id":310,"name":"Dr. Sudha Menon","specialty":"Endocrinologist","hospital":"Amrita Hospital, Kochi","city":"Kochi","experience":20,"degree":"MBBS, MD, DM (Endocrinology), DNB","rating":4.7,"fee":850,"slots":["09:00 AM","12:00 PM","04:30 PM"],"tags":_endo_tags,"avatar":"SM","color":"#06B6D4","comments":_c([("Nair P.","Excellent. Insulin pump management done well.",5,"Mar 2025"),("Radha K.","Daughter's Type 1 well controlled.",5,"Feb 2025"),("Thomas M.","Good consultation. Very detailed advice.",4,"Jan 2025")])},
]

# ── NEUROLOGISTS ──────────────────────────────────────────────────────────────
_neuro_tags = ["stroke","migraine","alzheimer's disease","meningitis","depression"]
DOCTORS_DB += [
 {"id":401,"name":"Dr. Suresh Kumar","specialty":"Neurologist","hospital":"NIMHANS, Bengaluru","city":"Bengaluru","experience":30,"degree":"MBBS, MD, DM (Neurology), FRCP","rating":4.9,"fee":700,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":_neuro_tags,"avatar":"SK","color":"#F59E0B","comments":_c([("Pradeep R.","Best neurologist in Bengaluru. Stroke recovery excellent.",5,"Mar 2025"),("Nalini S.","Very methodical. Found cause of my migraines.",5,"Feb 2025"),("Chandra M.","NIMHANS is best neurology institution in India.",5,"Jan 2025")])},
 {"id":402,"name":"Dr. Asha Kishore","specialty":"Neurologist","hospital":"Sree Chitra Tirunal Institute, Thiruvananthapuram","city":"Thiruvananthapuram","experience":25,"degree":"MBBS, MD, DM (Neurology), PhD, FIAN","rating":4.9,"fee":600,"slots":["09:30 AM","11:30 AM","03:30 PM"],"tags":_neuro_tags,"avatar":"AK","color":"#F59E0B","comments":_c([("Rajan N.","Top authority on movement disorders in Kerala.",5,"Mar 2025"),("Leela V.","Mother's Alzheimer's improved with her protocol.",5,"Feb 2025"),("Babu K.","Outstanding. Very patient with complex cases.",5,"Jan 2025")])},
 {"id":403,"name":"Dr. Pravina Shah","specialty":"Neurologist","hospital":"Jaslok Hospital, Mumbai","city":"Mumbai","experience":28,"degree":"MBBS, MD, DM (Neurology)","rating":4.8,"fee":1300,"slots":["08:30 AM","12:00 PM","04:30 PM"],"tags":_neuro_tags,"avatar":"PS","color":"#F59E0B","comments":_c([("Nikhil D.","Best migraine specialist in Mumbai.",5,"Mar 2025"),("Archana B.","Chronic migraines finally managed well.",5,"Feb 2025"),("Sanjay K.","Excellent. Thorough investigation.",4,"Jan 2025")])},
 {"id":404,"name":"Dr. M. V. Padma Srivastava","specialty":"Neurologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":28,"degree":"MBBS, MD, DM (Neurology), PhD, FAMS","rating":4.9,"fee":500,"slots":["09:00 AM","11:00 AM","02:30 PM"],"tags":_neuro_tags,"avatar":"MP","color":"#F59E0B","comments":_c([("Ravi S.","Stroke unit at AIIMS is world-class.",5,"Mar 2025"),("Usha B.","Very compassionate with stroke patients.",5,"Feb 2025"),("Anand T.","Excellent. Very thorough investigations.",5,"Jan 2025")])},
 {"id":405,"name":"Dr. S. Prabhakar","specialty":"Neurologist","hospital":"PGIMER, Chandigarh","city":"Chandigarh","experience":34,"degree":"MBBS, MD, DM (Neurology), FAMS","rating":4.8,"fee":650,"slots":["10:00 AM","01:00 PM","03:30 PM"],"tags":_neuro_tags,"avatar":"SP","color":"#F59E0B","comments":_c([("Harpal S.","Best neurologist in Punjab. Complex stroke managed brilliantly.",5,"Mar 2025"),("Gurjeet K.","Found subtle TIA signs early.",5,"Feb 2025"),("Ranjit B.","Excellent. Very updated with stroke protocols.",4,"Jan 2025")])},
 {"id":406,"name":"Dr. Neeraj Bhalla","specialty":"Neurologist","hospital":"BLK Super Speciality Hospital, Delhi","city":"Delhi","experience":20,"degree":"MBBS, MD, DM (Neurology), MRCP","rating":4.7,"fee":1100,"slots":["10:00 AM","01:30 PM","04:00 PM"],"tags":_neuro_tags,"avatar":"NB","color":"#F59E0B","comments":_c([("Vinod K.","Mother recovered remarkably under his care.",5,"Mar 2025"),("Shalini M.","Takes time with patient history. Very compassionate.",5,"Feb 2025"),("Aakash P.","Chronic migraine treatment finally working.",4,"Jan 2025")])},
 {"id":407,"name":"Dr. K. Bhanu","specialty":"Neurologist","hospital":"Yashoda Hospitals, Hyderabad","city":"Hyderabad","experience":22,"degree":"MBBS, MD, DM (Neurology)","rating":4.7,"fee":1000,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_neuro_tags,"avatar":"KB","color":"#F59E0B","comments":_c([("Venkatesan R.","Chronic migraines under control now.",5,"Mar 2025"),("Lalitha S.","Excellent stroke rehabilitation guidance.",4,"Feb 2025"),("Ramu K.","Good. Very accessible follow-up.",4,"Jan 2025")])},
 {"id":408,"name":"Dr. Lekha Pandit","specialty":"Neurologist","hospital":"KMC Hospital, Mangaluru","city":"Mangaluru","experience":24,"degree":"MBBS, MD, DM (Neurology), FIAN","rating":4.8,"fee":800,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":_neuro_tags,"avatar":"LP","color":"#F59E0B","comments":_c([("Ramesh N.","Leading neuroimmunology expert. Rare disease diagnosed.",5,"Mar 2025"),("Shobha K.","Very empathetic with dementia patients.",5,"Feb 2025"),("Suresh B.","Excellent. Very updated with latest research.",4,"Jan 2025")])},
 {"id":409,"name":"Dr. Uday Muthane","specialty":"Neurologist","hospital":"Manipal Hospitals, Bengaluru","city":"Bengaluru","experience":30,"degree":"MBBS, MD, DM (Neurology), FAMS","rating":4.7,"fee":1100,"slots":["10:30 AM","02:00 PM","05:00 PM"],"tags":_neuro_tags,"avatar":"UM","color":"#F59E0B","comments":_c([("Venkat S.","Expert in Parkinson's and Alzheimer's.",5,"Mar 2025"),("Meena R.","Very clear about treatment goals.",4,"Feb 2025"),("Ravi B.","Good. Caring approach to dementia.",4,"Jan 2025")])},
 {"id":410,"name":"Dr. Achal Srivastava","specialty":"Neurologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":26,"degree":"MBBS, MD, DM (Neurology)","rating":4.8,"fee":500,"slots":["09:30 AM","12:30 PM","03:30 PM"],"tags":_neuro_tags,"avatar":"AS","color":"#F59E0B","comments":_c([("Deepak M.","Brilliant at AIIMS. Diagnosed my rare condition.",5,"Mar 2025"),("Sunita R.","Very good for Alzheimer's management.",5,"Feb 2025"),("Rajesh P.","Excellent. Very detailed examination.",4,"Jan 2025")])},
]

# ── ONCOLOGISTS ───────────────────────────────────────────────────────────────
_onco_tags = ["breast cancer","colorectal cancer","lung cancer","pancreatic cancer","cervical cancer","prostate cancer"]
DOCTORS_DB += [
 {"id":501,"name":"Dr. Suresh Advani","specialty":"Medical Oncologist","hospital":"Jaslok Hospital, Mumbai","city":"Mumbai","experience":42,"degree":"MBBS, MD, DM (Medical Oncology), PhD, FACP","rating":4.9,"fee":2000,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_onco_tags,"avatar":"SA","color":"#EC4899","comments":_c([("Geeta M.","Pioneer of oncology in India. Breast cancer outcome excellent.",5,"Mar 2025"),("Ramesh T.","Knows every latest protocol. Saved my wife's life.",5,"Feb 2025"),("Leena D.","Most knowledgeable oncologist I have consulted.",5,"Jan 2025")])},
 {"id":502,"name":"Dr. Rajendra Badwe","specialty":"Surgical Oncologist","hospital":"Tata Memorial Hospital, Mumbai","city":"Mumbai","experience":35,"degree":"MBBS, MS (Surgery), MCh (Surgical Oncology), FRCS","rating":4.9,"fee":800,"slots":["08:00 AM","11:00 AM","02:00 PM"],"tags":_onco_tags,"avatar":"RB","color":"#EC4899","comments":_c([("Nirmala S.","Tata Memorial is best cancer centre in Asia.",5,"Mar 2025"),("Vijay K.","Colon surgery perfect. No recurrence in 3 years.",5,"Feb 2025"),("Sunanda P.","World class. Affordable at Tata Memorial.",5,"Jan 2025")])},
 {"id":503,"name":"Dr. P. K. Julka","specialty":"Radiation Oncologist","hospital":"Max Cancer Centre, Delhi","city":"Delhi","experience":32,"degree":"MBBS, MD (Radiotherapy), DNB, FICRO","rating":4.8,"fee":1500,"slots":["09:00 AM","12:30 PM","03:30 PM"],"tags":_onco_tags,"avatar":"PJ","color":"#EC4899","comments":_c([("Anita K.","Breast cancer in complete remission after radiation.",5,"Mar 2025"),("Sudhir M.","Very compassionate. Gives hope and clarity.",5,"Feb 2025"),("Rekha S.","Outstanding breast cancer expertise.",4,"Jan 2025")])},
 {"id":504,"name":"Dr. Shyam Aggarwal","specialty":"Medical Oncologist","hospital":"Sir Ganga Ram Hospital, Delhi","city":"Delhi","experience":27,"degree":"MBBS, MD, DM (Medical Oncology), MNAMS","rating":4.8,"fee":1400,"slots":["09:30 AM","01:30 PM","04:30 PM"],"tags":_onco_tags,"avatar":"SA","color":"#EC4899","comments":_c([("Harish B.","Prostate cancer with latest targeted therapy. Excellent.",5,"Mar 2025"),("Kavita R.","Emotional care as good as medical care.",5,"Feb 2025"),("Dinesh P.","Up to date with all latest cancer treatments.",4,"Jan 2025")])},
 {"id":505,"name":"Dr. Nita Nair","specialty":"Surgical Oncologist","hospital":"Tata Memorial Hospital, Mumbai","city":"Mumbai","experience":22,"degree":"MBBS, MS, MCh (Surgical Oncology), DNB","rating":4.9,"fee":900,"slots":["09:00 AM","12:00 PM","03:30 PM"],"tags":_onco_tags,"avatar":"NN","color":"#EC4899","comments":_c([("Sunita B.","Breast surgery with minimal trauma. Full recovery.",5,"Mar 2025"),("Meena K.","Very empathetic female oncologist.",5,"Feb 2025"),("Asha P.","Zero lymphedema after mastectomy. Excellent.",5,"Jan 2025")])},
 {"id":506,"name":"Dr. Vinod Raina","specialty":"Medical Oncologist","hospital":"Fortis Memorial Research Institute, Gurugram","city":"Gurugram","experience":30,"degree":"MBBS, MD, DM (Medical Oncology), FAMS","rating":4.8,"fee":1600,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_onco_tags,"avatar":"VR","color":"#EC4899","comments":_c([("Rekha S.","Chemotherapy protocol worked perfectly.",5,"Mar 2025"),("Naresh K.","Very clear about side effect management.",5,"Feb 2025"),("Pooja T.","Updated with global cancer guidelines.",4,"Jan 2025")])},
 {"id":507,"name":"Dr. Ashok Vaid","specialty":"Medical Oncologist","hospital":"Medanta, Gurugram","city":"Gurugram","experience":28,"degree":"MBBS, MD, DM (Medical Oncology), FRCPC (Canada)","rating":4.8,"fee":1800,"slots":["09:30 AM","01:30 PM","05:00 PM"],"tags":_onco_tags,"avatar":"AV","color":"#EC4899","comments":_c([("Subhash M.","International training adds great value. Excellent outcomes.",5,"Mar 2025"),("Geeta R.","Colon cancer to chemo all guided well.",5,"Feb 2025"),("Dinesh S.","Very thorough staging workup.",4,"Jan 2025")])},
 {"id":508,"name":"Dr. Hemant Malhotra","specialty":"Medical Oncologist","hospital":"SMS Medical College, Jaipur","city":"Jaipur","experience":26,"degree":"MBBS, MD, DM (Medical Oncology)","rating":4.7,"fee":700,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_onco_tags,"avatar":"HM","color":"#EC4899","comments":_c([("Prem L.","Treats rural patients with same dedication.",5,"Mar 2025"),("Kamla D.","Early cervical dysplasia caught by his diligent exam.",5,"Feb 2025"),("Bharat S.","Makes complex treatment understandable.",4,"Jan 2025")])},
 {"id":509,"name":"Dr. Tejinder Kataria","specialty":"Radiation Oncologist","hospital":"Medanta, Gurugram","city":"Gurugram","experience":24,"degree":"MBBS, MD (Radiotherapy), DNB, FICRO, FAMS","rating":4.8,"fee":1400,"slots":["10:00 AM","01:00 PM","04:30 PM"],"tags":_onco_tags,"avatar":"TK","color":"#EC4899","comments":_c([("Suresh K.","Prostate cancer IGRT done with precision.",5,"Mar 2025"),("Meena S.","Breast radiation with minimal side effects.",5,"Feb 2025"),("Anil B.","Professional. Excellent dosimetry team.",4,"Jan 2025")])},
 {"id":510,"name":"Dr. Neerja Bhatla","specialty":"Gynecologic Oncologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":30,"degree":"MBBS, MS (Obs & Gynae), FICOG, FRCOG, DNB","rating":4.9,"fee":600,"slots":["09:00 AM","11:00 AM","02:00 PM"],"tags":["cervical cancer","breast cancer"]+_onco_tags,"avatar":"NB","color":"#EC4899","comments":_c([("Anita M.","Cervical cancer stage 1. Treated perfectly.",5,"Mar 2025"),("Priya K.","Very thorough. Doesn't miss anything.",5,"Feb 2025"),("Kavita R.","Surgery had zero complications.",5,"Jan 2025")])},
]

# ── INFECTIOUS DISEASE ────────────────────────────────────────────────────────
_infect_tags = ["hiv/aids","malaria","dengue fever","hepatitis b","hepatitis c","influenza","covid-19","cholera","typhoid fever","meningitis","tuberculosis"]
DOCTORS_DB += [
 {"id":601,"name":"Dr. Ishwar Gilada","specialty":"Infectious Disease Specialist","hospital":"Unison Medicare, Mumbai","city":"Mumbai","experience":35,"degree":"MBBS, MD (Medicine), Diploma HIV Medicine, FICP","rating":4.9,"fee":1000,"slots":["10:00 AM","01:00 PM","04:30 PM"],"tags":_infect_tags,"avatar":"IG","color":"#10B981","comments":_c([("Anonymous.","Pioneer of HIV treatment in India. Non-judgmental.",5,"Mar 2025"),("Vikram S.","Best HIV specialist in India. Changed my life.",5,"Feb 2025"),("Priya N.","Very confidential. Excellent hepatitis treatment.",5,"Jan 2025")])},
 {"id":602,"name":"Dr. Om Srivastava","specialty":"Infectious Disease Specialist","hospital":"Jaslok Hospital, Mumbai","city":"Mumbai","experience":30,"degree":"MBBS, MD (Medicine), FICP, FIDSA","rating":4.8,"fee":1200,"slots":["09:30 AM","12:30 PM","03:30 PM"],"tags":_infect_tags,"avatar":"OS","color":"#10B981","comments":_c([("Rahul K.","Diagnosed my typhoid quickly when others couldn't.",5,"Mar 2025"),("Sneha M.","Dengue treated very effectively.",5,"Feb 2025"),("Amit D.","Thorough. Very systematic approach.",4,"Jan 2025")])},
 {"id":603,"name":"Dr. Subramanian Swaminathan","specialty":"Infectious Disease Specialist","hospital":"ID Medical Centre, Chennai","city":"Chennai","experience":28,"degree":"MBBS, MD (Pulmonary Medicine), FIDSA, FRCP","rating":4.8,"fee":1100,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":_infect_tags,"avatar":"SS","color":"#10B981","comments":_c([("Suresh N.","Best tropical disease specialist in Chennai.",5,"Mar 2025"),("Kavita R.","HIV management protocol excellent. Very supportive.",5,"Feb 2025"),("Raju K.","Good. Very systematic infection workup.",4,"Jan 2025")])},
 {"id":604,"name":"Dr. Camilla Rodrigues","specialty":"Microbiologist & ID Specialist","hospital":"P. D. Hinduja Hospital, Mumbai","city":"Mumbai","experience":30,"degree":"MBBS, MD (Microbiology), PhD, FAMS, FRCPath","rating":4.9,"fee":1000,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_infect_tags,"avatar":"CR","color":"#10B981","comments":_c([("Priya S.","Leading microbiologist in India. Drug-resistant TB managed brilliantly.",5,"Mar 2025"),("Nitin K.","Very helpful in antibiotic stewardship.",5,"Feb 2025"),("Anil M.","Outstanding expertise. Great research background.",5,"Jan 2025")])},
 {"id":605,"name":"Dr. Sanjeev Misra","specialty":"Infectious Disease Specialist","hospital":"AIIMS, Jodhpur","city":"Jodhpur","experience":22,"degree":"MBBS, MD, ID Fellowship (USA)","rating":4.8,"fee":500,"slots":["09:00 AM","11:00 AM","02:30 PM"],"tags":_infect_tags,"avatar":"SM","color":"#10B981","comments":_c([("Ratan S.","Severe malaria in my son treated effectively.",5,"Mar 2025"),("Geeta B.","Updated with tropical disease protocols.",5,"Feb 2025"),("Tarun M.","Good. Rare expertise in cholera management.",4,"Jan 2025")])},
 {"id":606,"name":"Dr. Vijay Yewale","specialty":"Pediatric ID Specialist","hospital":"DY Patil Hospital, Navi Mumbai","city":"Navi Mumbai","experience":25,"degree":"MBBS, MD (Pediatrics), ID Fellowship","rating":4.7,"fee":900,"slots":["10:30 AM","01:30 PM","05:00 PM"],"tags":_infect_tags,"avatar":"VY","color":"#10B981","comments":_c([("Neeta P.","Best pediatric ID doctor. Kids always in safe hands.",5,"Mar 2025"),("Samir K.","Very gentle with children. Excellent dengue diagnosis.",5,"Feb 2025"),("Pallavi R.","Good. Very thorough with vaccination schedules.",4,"Jan 2025")])},
 {"id":607,"name":"Dr. Amita Jain","specialty":"Microbiologist & ID Specialist","hospital":"KGMU, Lucknow","city":"Lucknow","experience":24,"degree":"MBBS, MD (Microbiology), PhD, FAMS","rating":4.8,"fee":600,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_infect_tags,"avatar":"AJ","color":"#10B981","comments":_c([("Vikash S.","Leading expert in drug-resistant TB.",5,"Mar 2025"),("Prerna K.","Very helpful for understanding infection lab reports.",5,"Feb 2025"),("Sanjay M.","Excellent for rare infections.",4,"Jan 2025")])},
 {"id":608,"name":"Dr. Vishal Nahar","specialty":"Infectious Disease Specialist","hospital":"Prince Aly Khan Hospital, Mumbai","city":"Mumbai","experience":18,"degree":"MBBS, MD, FIDSA, FICP","rating":4.7,"fee":1100,"slots":["10:00 AM","01:30 PM","04:30 PM"],"tags":_infect_tags,"avatar":"VN","color":"#10B981","comments":_c([("Rashid K.","Updated with HIV treatment advances. Excellent.",5,"Mar 2025"),("Ananya M.","Good for post-COVID management.",4,"Feb 2025"),("Deepak R.","Clear treatment plan.",4,"Jan 2025")])},
 {"id":609,"name":"Dr. Murali Mohan Reddy","specialty":"Infectious Disease Specialist","hospital":"Yashoda Hospitals, Hyderabad","city":"Hyderabad","experience":20,"degree":"MBBS, MD, DNB, FIDSA","rating":4.7,"fee":850,"slots":["09:00 AM","12:00 PM","04:30 PM"],"tags":_infect_tags,"avatar":"MR","color":"#10B981","comments":_c([("Srinivas K.","Treated my severe dengue shock syndrome. Saved my life.",5,"Mar 2025"),("Bhavana R.","Very good for malaria treatment.",5,"Feb 2025"),("Venkat B.","Good. Systematic fever workup approach.",4,"Jan 2025")])},
 {"id":610,"name":"Dr. M. Valsan","specialty":"Infectious Disease Specialist","hospital":"Amrita Hospital, Kochi","city":"Kochi","experience":26,"degree":"MBBS, MD, FIDSA","rating":4.8,"fee":900,"slots":["09:30 AM","12:30 PM","03:30 PM"],"tags":_infect_tags,"avatar":"MV","color":"#10B981","comments":_c([("George T.","Excellent infectious disease specialist in Kerala.",5,"Mar 2025"),("Leena K.","Dengue managed perfectly. Very attentive.",5,"Feb 2025"),("Binu M.","Good. Very knowledgeable about rare infections.",4,"Jan 2025")])},
]

# ── HEPATOLOGISTS ─────────────────────────────────────────────────────────────
_hepato_tags = ["hepatitis b","hepatitis c","liver cirrhosis"]
DOCTORS_DB += [
 {"id":701,"name":"Dr. Shiv Kumar Sarin","specialty":"Hepatologist","hospital":"ILBS, New Delhi","city":"Delhi","experience":38,"degree":"MBBS, MD, DM (Gastroenterology), DSc, FRCP, FNA","rating":4.9,"fee":1500,"slots":["09:00 AM","11:30 AM","03:00 PM"],"tags":_hepato_tags,"avatar":"SS","color":"#F97316","comments":_c([("Arun M.","World's best for HBV. Liver enzymes now normal.",5,"Mar 2025"),("Savita K.","Pioneered many liver treatments.",5,"Feb 2025"),("Naveen R.","ILBS is India's premier liver institute.",5,"Jan 2025")])},
 {"id":702,"name":"Dr. D. N. Reddy","specialty":"Gastroenterologist / Hepatologist","hospital":"Asian Institute of Gastroenterology, Hyderabad","city":"Hyderabad","experience":35,"degree":"MBBS, MD, DM (Gastroenterology), FAMS, FASGE","rating":4.9,"fee":1200,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":_hepato_tags+["gastroenteritis","colorectal cancer","appendicitis"],"avatar":"DR","color":"#F97316","comments":_c([("Rajesh M.","Globally recognized. Pioneered endoscopy techniques.",5,"Mar 2025"),("Lakshmi P.","Liver cirrhosis treatment outstanding.",5,"Feb 2025"),("Srinivas K.","World class gastroenterology at AIG.",5,"Jan 2025")])},
 {"id":703,"name":"Dr. Abhijit Chowdhury","specialty":"Hepatologist","hospital":"IPGMER & SSKM Hospital, Kolkata","city":"Kolkata","experience":28,"degree":"MBBS, MD, DM (Gastroenterology), PhD","rating":4.8,"fee":600,"slots":["09:30 AM","12:00 PM","04:00 PM"],"tags":_hepato_tags,"avatar":"AC","color":"#F97316","comments":_c([("Subrata D.","Hepatitis C cured with new antivirals.",5,"Mar 2025"),("Mita B.","Very thorough. Explained liver cirrhosis in detail.",5,"Feb 2025"),("Tapan M.","Very updated with hepatitis advances.",4,"Jan 2025")])},
 {"id":704,"name":"Dr. Subrat Kumar Acharya","specialty":"Hepatologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":36,"degree":"MBBS, MD, DM (Gastroenterology), FAMS, FRCP, FNA","rating":4.9,"fee":600,"slots":["09:00 AM","11:00 AM","02:00 PM"],"tags":_hepato_tags,"avatar":"SA","color":"#F97316","comments":_c([("Rohan M.","Most experienced liver specialist in India.",5,"Mar 2025"),("Anita S.","Acute liver failure managed brilliantly at AIIMS.",5,"Feb 2025"),("Deepak R.","World-class hepatology. Dr. Acharya is the best.",5,"Jan 2025")])},
 {"id":705,"name":"Dr. Anil Arora","specialty":"Hepatologist","hospital":"Sir Ganga Ram Hospital, Delhi","city":"Delhi","experience":30,"degree":"MBBS, MD, DM (Gastroenterology), FICP, FSGEI","rating":4.8,"fee":1100,"slots":["09:30 AM","12:30 PM","04:00 PM"],"tags":_hepato_tags,"avatar":"AA","color":"#F97316","comments":_c([("Pawan S.","Hepatitis C is now undetectable.",5,"Mar 2025"),("Alka R.","Very thorough liver biopsy follow-up.",5,"Feb 2025"),("Sudhir T.","Clear on treatment options.",4,"Jan 2025")])},
 {"id":706,"name":"Dr. Cyriac Abby Philips","specialty":"Hepatologist","hospital":"Rajagiri Hospital, Kochi","city":"Kochi","experience":16,"degree":"MBBS, MD, DM (Hepatology), MRCP","rating":4.8,"fee":1000,"slots":["10:00 AM","01:30 PM","04:30 PM"],"tags":_hepato_tags,"avatar":"CP","color":"#F97316","comments":_c([("Jose M.","Young but exceptionally knowledgeable.",5,"Mar 2025"),("Anju K.","Alcohol-related cirrhosis managed with great care.",5,"Feb 2025"),("Thomas P.","Very updated with latest hepatology guidelines.",4,"Jan 2025")])},
 {"id":707,"name":"Dr. Mohandas Mallath","specialty":"Gastroenterologist / Hepatologist","hospital":"Tata Medical Center, Kolkata","city":"Kolkata","experience":30,"degree":"MBBS, MD, DM (Gastroenterology), MRCP, FRCP","rating":4.8,"fee":1100,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_hepato_tags+["colorectal cancer"],"avatar":"MM","color":"#F97316","comments":_c([("Protap S.","Excellent hepatologist and gastroenterologist.",5,"Mar 2025"),("Rina C.","Hepatitis B management excellent.",5,"Feb 2025"),("Ashim D.","Very updated with hepatitis C cure protocols.",4,"Jan 2025")])},
]

# ── NEPHROLOGISTS ─────────────────────────────────────────────────────────────
_nephro_tags = ["chronic kidney disease","hypertension","diabetes type 2","diabetes type 1","uti"]
DOCTORS_DB += [
 {"id":801,"name":"Dr. Georgi Abraham","specialty":"Nephrologist","hospital":"Madras Medical Mission, Chennai","city":"Chennai","experience":35,"degree":"MBBS, MD, DM (Nephrology), FRCP, FAMS","rating":4.9,"fee":1000,"slots":["09:30 AM","11:30 AM","02:30 PM"],"tags":_nephro_tags,"avatar":"GA","color":"#3B82F6","comments":_c([("Vincent P.","Pioneer of kidney transplant in South India.",5,"Mar 2025"),("Mary S.","My transplant was perfect. Living normal life.",5,"Feb 2025"),("Joseph K.","Excellent. Very empathetic nephrologist.",5,"Jan 2025")])},
 {"id":802,"name":"Dr. K. S. Nayak","specialty":"Nephrologist","hospital":"Tanvir Hospital, Hyderabad","city":"Hyderabad","experience":30,"degree":"MBBS, MD, DM (Nephrology), FASN","rating":4.8,"fee":900,"slots":["09:00 AM","12:00 PM","03:30 PM"],"tags":_nephro_tags,"avatar":"KN","color":"#3B82F6","comments":_c([("Suresh R.","Delayed my dialysis by 3 years. Best nephrologist.",5,"Mar 2025"),("Padma V.","Very compassionate. Explains dialysis options clearly.",5,"Feb 2025"),("Raju B.","Creatinine levels stabilized under his care.",4,"Jan 2025")])},
 {"id":803,"name":"Dr. Vivekanand Jha","specialty":"Nephrologist","hospital":"George Institute, Hyderabad","city":"Hyderabad","experience":28,"degree":"MBBS, MD, DM (Nephrology), PhD, FRCP","rating":4.9,"fee":1100,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_nephro_tags,"avatar":"VJ","color":"#3B82F6","comments":_c([("Suresh T.","Global leader in CKD research. Outstanding clinical care.",5,"Mar 2025"),("Rekha M.","Kidney function stabilized significantly.",5,"Feb 2025"),("Naresh B.","Very thorough research-based approach.",4,"Jan 2025")])},
 {"id":804,"name":"Dr. Raja Ramachandran","specialty":"Nephrologist","hospital":"PGIMER, Chandigarh","city":"Chandigarh","experience":20,"degree":"MBBS, MD, DM (Nephrology), DNB, MRCP","rating":4.8,"fee":650,"slots":["09:00 AM","12:30 PM","03:30 PM"],"tags":_nephro_tags,"avatar":"RR","color":"#3B82F6","comments":_c([("Gurnam S.","Excellent. Very updated with CKD management.",5,"Mar 2025"),("Harleen K.","IgA nephropathy managed brilliantly.",5,"Feb 2025"),("Jaspreet B.","Good. Very clear on diet restrictions.",4,"Jan 2025")])},
 {"id":805,"name":"Dr. Sanjeev Gulati","specialty":"Nephrologist","hospital":"Fortis Hospital, Delhi","city":"Delhi","experience":22,"degree":"MBBS, MD (Pediatrics), DM (Nephrology), DNB","rating":4.7,"fee":1200,"slots":["10:00 AM","01:30 PM","04:30 PM"],"tags":_nephro_tags,"avatar":"SG","color":"#3B82F6","comments":_c([("Vinod M.","Son's CKD managed very well.",5,"Mar 2025"),("Asha T.","Very thorough kidney disease monitoring.",4,"Feb 2025"),("Pankaj S.","Good. Very logical treatment approach.",4,"Jan 2025")])},
]

# ── PSYCHIATRISTS ─────────────────────────────────────────────────────────────
_psych_tags = ["depression","alzheimer's disease","anxiety"]
DOCTORS_DB += [
 {"id":901,"name":"Dr. Harish Shetty","specialty":"Psychiatrist","hospital":"Dr. L. H. Hiranandani Hospital, Mumbai","city":"Mumbai","experience":28,"degree":"MBBS, MD (Psychiatry), DPM","rating":4.9,"fee":1500,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_psych_tags,"avatar":"HS","color":"#A78BFA","comments":_c([("Pooja R.","Changed my life. Severely depressed before. Thriving now.",5,"Mar 2025"),("Anonymous.","Non-judgmental and very empathetic. Best in Mumbai.",5,"Feb 2025"),("Rahul N.","Excellent holistic approach to mental health.",5,"Jan 2025")])},
 {"id":902,"name":"Dr. Soumitra Pathare","specialty":"Psychiatrist","hospital":"Centre for Mental Health Law & Policy, Pune","city":"Pune","experience":24,"degree":"MBBS, MD (Psychiatry), MRCPsych (UK)","rating":4.8,"fee":1200,"slots":["09:30 AM","12:30 PM","03:30 PM"],"tags":_psych_tags,"avatar":"SP","color":"#A78BFA","comments":_c([("Sucheta M.","Helped me navigate severe post-partum depression.",5,"Mar 2025"),("Vivek A.","No over-medication. Therapy focused. Very scientific.",5,"Feb 2025"),("Nalini P.","Excellent. Very patient and understanding.",4,"Jan 2025")])},
 {"id":903,"name":"Dr. Nimesh Desai","specialty":"Psychiatrist","hospital":"IHBAS, Delhi","city":"Delhi","experience":30,"degree":"MBBS, MD (Psychiatry), FAMS, MRCPsych (UK)","rating":4.8,"fee":600,"slots":["09:00 AM","11:00 AM","02:00 PM"],"tags":_psych_tags,"avatar":"ND","color":"#A78BFA","comments":_c([("Geeta S.","Mother's late-stage dementia managed with dignity.",5,"Mar 2025"),("Arun M.","Very caring psychiatric rehabilitation approach.",5,"Feb 2025"),("Sunita R.","Outstanding geriatric psychiatry expertise.",4,"Jan 2025")])},
 {"id":904,"name":"Dr. Shyam Sundar","specialty":"Psychiatrist","hospital":"NIMHANS, Bengaluru","city":"Bengaluru","experience":28,"degree":"MBBS, MD (Psychiatry), DPM, PhD","rating":4.9,"fee":700,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":_psych_tags,"avatar":"SS","color":"#A78BFA","comments":_c([("Priya N.","NIMHANS is the best mental health institution in India.",5,"Mar 2025"),("Kavitha S.","Recovered from severe depression with his help.",5,"Feb 2025"),("Ravi B.","Very evidence-based. No unnecessary medication.",4,"Jan 2025")])},
 {"id":905,"name":"Dr. Alok Sarin","specialty":"Psychiatrist","hospital":"Sitaram Bhartia Institute, Delhi","city":"Delhi","experience":32,"degree":"MBBS, MD (Psychiatry), MPhil","rating":4.8,"fee":1400,"slots":["10:30 AM","02:00 PM","05:00 PM"],"tags":_psych_tags,"avatar":"AS","color":"#A78BFA","comments":_c([("Nidhi S.","Combined therapy and medication perfectly.",5,"Mar 2025"),("Rohit K.","Very insightful. Understands root causes.",5,"Feb 2025"),("Meena T.","Changed how I understand my own mental health.",5,"Jan 2025")])},
]

# ── GENERAL PHYSICIANS ────────────────────────────────────────────────────────
_gp_tags = ["influenza","covid-19","anemia","gastroenteritis","hypertension","uti","dengue fever","typhoid fever","malaria"]
DOCTORS_DB += [
 {"id":1001,"name":"Dr. K. K. Aggarwal","specialty":"General Physician","hospital":"Moolchand Hospital, Delhi","city":"Delhi","experience":35,"degree":"MBBS, MD (Medicine), FICP, FISE, FAMS","rating":4.8,"fee":800,"slots":["09:00 AM","12:00 PM","03:00 PM","05:00 PM"],"tags":_gp_tags,"avatar":"KA","color":"#0EA5E9","comments":_c([("Rakesh S.","One of India's most respected physicians.",5,"Mar 2025"),("Sunita K.","Enormous experience across all medical conditions.",5,"Feb 2025"),("Deepak M.","Knowledgeable about post-COVID long-term effects.",4,"Jan 2025")])},
 {"id":1002,"name":"Dr. Ravi Shankar Sharma","specialty":"General Physician","hospital":"Safdarjung Hospital, Delhi","city":"Delhi","experience":20,"degree":"MBBS, MD (General Medicine), FICP","rating":4.6,"fee":300,"slots":["09:00 AM","11:00 AM","02:00 PM","04:00 PM"],"tags":_gp_tags,"avatar":"RS","color":"#0EA5E9","comments":_c([("Manoj K.","Excellent government doctor. Dedicated.",5,"Mar 2025"),("Sunita B.","Treats all patients equally regardless of background.",4,"Feb 2025"),("Raju P.","Long wait but very thorough.",4,"Jan 2025")])},
 {"id":1003,"name":"Dr. Sumana Manohar","specialty":"General Physician","hospital":"Columbia Asia Hospital, Bengaluru","city":"Bengaluru","experience":18,"degree":"MBBS, MD (General Medicine), DNB","rating":4.7,"fee":900,"slots":["09:30 AM","12:30 PM","04:30 PM"],"tags":_gp_tags,"avatar":"SM","color":"#0EA5E9","comments":_c([("Anjali P.","Very thorough annual health checkup.",5,"Mar 2025"),("Pradeep N.","Good for UTI management. Quick treatment.",5,"Feb 2025"),("Ramesh K.","Accessible and caring. Good follow-up.",4,"Jan 2025")])},
 {"id":1004,"name":"Dr. Priya Bhave","specialty":"General Physician","hospital":"Hiranandani Hospital, Mumbai","city":"Mumbai","experience":16,"degree":"MBBS, MD (General Medicine)","rating":4.7,"fee":1000,"slots":["10:00 AM","01:30 PM","05:00 PM"],"tags":_gp_tags,"avatar":"PB","color":"#0EA5E9","comments":_c([("Suresh M.","Very empathetic. Excellent for long-term chronic care.",5,"Mar 2025"),("Rekha N.","Good anemia management. Diet advice very helpful.",4,"Feb 2025"),("Amit T.","Thorough consultation. Very patient.",4,"Jan 2025")])},
 {"id":1005,"name":"Dr. T. S. Kler","specialty":"General Physician","hospital":"Fortis Heart Hospital, Delhi","city":"Delhi","experience":27,"degree":"MBBS, MD, DM (Cardiology), FACC, FSCAI","rating":4.8,"fee":1100,"slots":["10:00 AM","01:00 PM","04:00 PM"],"tags":_gp_tags+["coronary artery disease","hypertension"],"avatar":"TK","color":"#0EA5E9","comments":_c([("Sudhir B.","Treated post-COVID cardiac complications effectively.",5,"Mar 2025"),("Nisha R.","Caught silent condition during annual checkup.",5,"Feb 2025"),("Ajay P.","Updated with post-COVID management protocols.",4,"Jan 2025")])},
]

# ── SURGEONS ──────────────────────────────────────────────────────────────────
_surg_tags = ["appendicitis","colorectal cancer","gastroenteritis","obesity"]
DOCTORS_DB += [
 {"id":1101,"name":"Dr. G. K. Mani","specialty":"General & Laparoscopic Surgeon","hospital":"Global Hospitals, Chennai","city":"Chennai","experience":25,"degree":"MBBS, MS (General Surgery), FMAS, FIAGES","rating":4.8,"fee":900,"slots":["08:00 AM","11:00 AM","03:00 PM"],"tags":_surg_tags,"avatar":"GM","color":"#14B8A6","comments":_c([("Suresh K.","Appendix removal keyhole — next day discharge.",5,"Mar 2025"),("Radha M.","Colon surgery with minimal complications.",5,"Feb 2025"),("Karthik N.","Clear post-op instructions. Great skill.",4,"Jan 2025")])},
 {"id":1102,"name":"Dr. R. K. Mishra","specialty":"Laparoscopic & Bariatric Surgeon","hospital":"World Laparoscopy Hospital, Gurugram","city":"Gurugram","experience":28,"degree":"MBBS, MS (General Surgery), FMAS, FALS, PhD","rating":4.8,"fee":1000,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":_surg_tags,"avatar":"RM","color":"#14B8A6","comments":_c([("Anil B.","World's best laparoscopic surgeon.",5,"Mar 2025"),("Seeta P.","Bariatric surgery. Lost 40 kg. Life changed.",5,"Feb 2025"),("Deepak S.","Minimally invasive. Back to work in one week.",5,"Jan 2025")])},
 {"id":1103,"name":"Dr. Prakash Muthukumar","specialty":"Colorectal Surgeon","hospital":"Apollo Hospitals, Chennai","city":"Chennai","experience":22,"degree":"MBBS, MS (General Surgery), MCh (Colorectal Surgery), FRCS","rating":4.8,"fee":1300,"slots":["09:00 AM","12:30 PM","03:30 PM"],"tags":_surg_tags,"avatar":"PM","color":"#14B8A6","comments":_c([("Suresh R.","Best colorectal surgeon in Chennai. Excellent.",5,"Mar 2025"),("Meena K.","Stoma avoided with his expertise. Brilliant.",5,"Feb 2025"),("Ravi N.","Very clear about surgical options.",4,"Jan 2025")])},
 {"id":1104,"name":"Dr. Ajay Mandal","specialty":"General Surgeon","hospital":"NRS Medical College, Kolkata","city":"Kolkata","experience":24,"degree":"MBBS, MS (General Surgery), FACS","rating":4.7,"fee":600,"slots":["09:30 AM","01:30 PM","04:30 PM"],"tags":_surg_tags,"avatar":"AM","color":"#14B8A6","comments":_c([("Bhaskar D.","Emergency appendicitis surgery. Very quick.",5,"Mar 2025"),("Tanmoy S.","Affordable and high quality care.",4,"Feb 2025"),("Sanjay M.","Thorough pre-operative workup.",4,"Jan 2025")])},
]

# ── GYNECOLOGISTS ─────────────────────────────────────────────────────────────
DOCTORS_DB += [
 {"id":1201,"name":"Dr. Laila Patel","specialty":"Gynecologist","hospital":"Kokilaben Ambani Hospital, Mumbai","city":"Mumbai","experience":22,"degree":"MBBS, DGO, MD (Obstetrics & Gynecology), FICOG","rating":4.8,"fee":1100,"slots":["10:00 AM","01:30 PM","04:30 PM"],"tags":["cervical cancer","uti","anemia","pcod"],"avatar":"LP","color":"#F472B6","comments":_c([("Seema D.","Early cervical dysplasia caught. Very thorough.",5,"Mar 2025"),("Nisha T.","Very caring and professional.",5,"Feb 2025"),("Pooja N.","Good. Very experienced.",4,"Jan 2025")])},
 {"id":1202,"name":"Dr. Alka Kriplani","specialty":"Gynecologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":30,"degree":"MBBS, MS (Obstetrics & Gynecology), FICOG, FRCOG","rating":4.8,"fee":600,"slots":["09:30 AM","12:00 PM","03:00 PM"],"tags":["cervical cancer","uti","anemia"],"avatar":"AK","color":"#F472B6","comments":_c([("Vandana S.","Outstanding. 30 years at AIIMS.",5,"Mar 2025"),("Ritu M.","Diagnosed my condition after years of misdiagnosis.",5,"Feb 2025"),("Kamini P.","Very empathetic with women's health.",4,"Jan 2025")])},
 {"id":1203,"name":"Dr. Sunita Tandulwadkar","specialty":"Gynecologist","hospital":"Ruby Hall Clinic, Pune","city":"Pune","experience":26,"degree":"MBBS, DGO, MD (Obstetrics & Gynecology), FICOG, FICS","rating":4.8,"fee":1000,"slots":["09:00 AM","12:00 PM","04:00 PM"],"tags":["cervical cancer","uti","endometriosis"],"avatar":"ST","color":"#F472B6","comments":_c([("Savita R.","Excellent fertility specialist and cancer screening.",5,"Mar 2025"),("Meena P.","Endometriosis treatment excellent. Minimal scarring.",5,"Feb 2025"),("Deepa K.","Good for all women's health needs.",4,"Jan 2025")])},
]

# ── UROLOGISTS ────────────────────────────────────────────────────────────────
DOCTORS_DB += [
 {"id":1301,"name":"Dr. Mahesh Desai","specialty":"Urologist","hospital":"Muljibhai Patel Urological Hospital, Nadiad","city":"Nadiad","experience":38,"degree":"MBBS, MS (Urology), MCh, FRCS, FACS","rating":4.9,"fee":900,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":["uti","prostate cancer","chronic kidney disease"],"avatar":"MD","color":"#6366F1","comments":_c([("Dhiraj P.","World renowned urologist. Zero complications.",5,"Mar 2025"),("Ravi S.","Best urological hospital in Asia.",5,"Feb 2025"),("Kantibhai M.","Prostate surgery. Full recovery in 4 weeks.",5,"Jan 2025")])},
 {"id":1302,"name":"Dr. Anant Kumar","specialty":"Urologist","hospital":"Max Super Speciality Hospital, Delhi","city":"Delhi","experience":30,"degree":"MBBS, MS (Urology), MCh (Urology), FRCS","rating":4.8,"fee":1300,"slots":["09:30 AM","01:00 PM","04:30 PM"],"tags":["uti","prostate cancer","chronic kidney disease"],"avatar":"AK","color":"#6366F1","comments":_c([("Suresh V.","Prostate surgery done with robotic precision.",5,"Mar 2025"),("Neeraj B.","Clear about treatment options. No unnecessary procedures.",5,"Feb 2025"),("Pawan K.","Good. Experienced with complex urology.",4,"Jan 2025")])},
 {"id":1303,"name":"Dr. M. S. Ansari","specialty":"Urologist","hospital":"SGPGI, Lucknow","city":"Lucknow","experience":24,"degree":"MBBS, MS (Urology), MCh (Urology)","rating":4.7,"fee":550,"slots":["09:30 AM","12:30 PM","04:00 PM"],"tags":["uti","prostate cancer","chronic kidney disease"],"avatar":"MA","color":"#6366F1","comments":_c([("Ramesh S.","Very skilled urologist at SGPGI.",5,"Mar 2025"),("Geeta L.","Good for complex UTI cases.",4,"Feb 2025"),("Dilip M.","Affordable and excellent quality.",4,"Jan 2025")])},
]

# ── HEMATOLOGISTS ─────────────────────────────────────────────────────────────
DOCTORS_DB += [
 {"id":1401,"name":"Dr. Navin Khattry","specialty":"Hematologist / BMT Specialist","hospital":"ACTREC Tata Memorial, Mumbai","city":"Mumbai","experience":20,"degree":"MBBS, MD (Medicine), DM (Clinical Hematology), DNB","rating":4.9,"fee":1000,"slots":["09:00 AM","12:00 PM","03:00 PM"],"tags":["anemia","hiv/aids"],"avatar":"NK","color":"#DC2626","comments":_c([("Meena K.","Daughter's bone marrow transplant done successfully.",5,"Mar 2025"),("Suresh B.","World class care at Tata Memorial.",5,"Feb 2025"),("Pratibha R.","Very compassionate with blood cancer patients.",5,"Jan 2025")])},
 {"id":1402,"name":"Dr. Tulika Seth","specialty":"Hematologist","hospital":"AIIMS, New Delhi","city":"Delhi","experience":18,"degree":"MBBS, MD (Pathology), DM (Clinical Hematology), PhD","rating":4.8,"fee":500,"slots":["09:30 AM","11:30 AM","02:30 PM"],"tags":["anemia","hiv/aids"],"avatar":"TS","color":"#DC2626","comments":_c([("Vivek M.","Severe anemia treated perfectly. Full recovery.",5,"Mar 2025"),("Sunita P.","Very knowledgeable about thalassemia.",5,"Feb 2025"),("Manish K.","Good. Very thorough blood work analysis.",4,"Jan 2025")])},
 {"id":1403,"name":"Dr. Dinesh Bhurani","specialty":"Hematologist","hospital":"Rajiv Gandhi Cancer Institute, Delhi","city":"Delhi","experience":22,"degree":"MBBS, MD, DM (Clinical Hematology), DNB","rating":4.8,"fee":1200,"slots":["09:00 AM","12:00 PM","03:30 PM"],"tags":["anemia","hiv/aids"],"avatar":"DB","color":"#DC2626","comments":_c([("Rakesh S.","Bone marrow transplant done with excellent outcome.",5,"Mar 2025"),("Kavita M.","Very caring during difficult blood cancer journey.",5,"Feb 2025"),("Anil P.","Very skilled in stem cell transplantation.",4,"Jan 2025")])},
]

# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────
DISEASE_TO_TAGS = {
    "coronary artery disease": ["coronary artery disease","heart failure","cardiac surgery","hypertension","peripheral artery disease"],
    "stroke": ["stroke","meningitis","hypertension"],
    "hypertension": ["hypertension","coronary artery disease","chronic kidney disease","stroke"],
    "heart failure": ["heart failure","coronary artery disease","hypertension"],
    "peripheral artery disease": ["peripheral artery disease","coronary artery disease"],
    "copd": ["copd","asthma","lung cancer","tuberculosis","pneumonia"],
    "asthma": ["asthma","copd","pneumonia"],
    "pneumonia": ["pneumonia","tuberculosis","copd","asthma","covid-19"],
    "tuberculosis": ["tuberculosis","hiv/aids","pneumonia","copd"],
    "lung cancer": ["lung cancer","copd","colorectal cancer"],
    "diabetes type 1": ["diabetes type 1","diabetes type 2","obesity"],
    "diabetes type 2": ["diabetes type 2","diabetes type 1","obesity","chronic kidney disease"],
    "chronic kidney disease": ["chronic kidney disease","hypertension","diabetes type 2","uti"],
    "liver cirrhosis": ["liver cirrhosis","hepatitis b","hepatitis c"],
    "obesity": ["obesity","diabetes type 2","diabetes type 1"],
    "alzheimer's disease": ["alzheimer's disease","depression","stroke","anxiety"],
    "hiv/aids": ["hiv/aids","tuberculosis","hepatitis b","hepatitis c","anemia"],
    "malaria": ["malaria","dengue fever","typhoid fever","cholera"],
    "dengue fever": ["dengue fever","malaria","typhoid fever"],
    "hepatitis b": ["hepatitis b","hepatitis c","liver cirrhosis","hiv/aids"],
    "hepatitis c": ["hepatitis c","hepatitis b","liver cirrhosis"],
    "influenza": ["influenza","covid-19","pneumonia","asthma"],
    "covid-19": ["covid-19","influenza","pneumonia","asthma"],
    "cholera": ["cholera","typhoid fever","gastroenteritis","malaria"],
    "typhoid fever": ["typhoid fever","malaria","dengue fever","cholera"],
    "meningitis": ["meningitis","stroke","tuberculosis","hiv/aids"],
    "breast cancer": ["breast cancer","cervical cancer","colorectal cancer"],
    "colorectal cancer": ["colorectal cancer","appendicitis","gastroenteritis"],
    "prostate cancer": ["prostate cancer","uti","chronic kidney disease"],
    "pancreatic cancer": ["pancreatic cancer","liver cirrhosis","colorectal cancer"],
    "cervical cancer": ["cervical cancer","uti","breast cancer"],
    "migraine": ["migraine","stroke","alzheimer's disease"],
    "anemia": ["anemia","hiv/aids"],
    "gastroenteritis": ["gastroenteritis","cholera","appendicitis"],
    "uti": ["uti","chronic kidney disease","prostate cancer","cervical cancer"],
    "depression": ["depression","alzheimer's disease","anxiety"],
    "appendicitis": ["appendicitis","colorectal cancer","gastroenteritis"],
}

def get_doctors_for_disease(disease_name, limit=10):
    dn = disease_name.lower()
    search_tags = DISEASE_TO_TAGS.get(dn, [dn])
    scored = []
    for doc in DOCTORS_DB:
        score = 0
        for tag in doc["tags"]:
            if tag == dn:
                score += 5
            elif tag in search_tags:
                score += 2
        if score > 0:
            scored.append((score, doc))
    scored.sort(key=lambda x: (-x[0], -x[1]["rating"], -x[1]["experience"]))
    return [d for _, d in scored[:limit]]

def get_all_doctors():
    return sorted(DOCTORS_DB, key=lambda d: (-d["rating"], -d["experience"]))

def get_doctor_by_id(doc_id):
    return next((d for d in DOCTORS_DB if d["id"] == doc_id), None)

def get_specialties():
    return sorted(set(d["specialty"] for d in DOCTORS_DB))
